### ISSUE TITLE
Cant't create.

### ISSUE THREAD

**Issue by xxxkilldogxxx** [jonashagstedt/swampdragon#109]
When using my sendMessage() function i keep getting this error:

    $scope.sendMessage = function(message) {
        console.log("GETTING SEND MESSAGE FUNCTION");
        $dragon.create('message-route', {message:'test'}).then(function(response) {
            console.log(response);
        }).catch(function(errors) {
            console.log(errors)
        });
    }

This is the error I keep getting... I'm very new to angularJS so not really sure what I'm doing wrong.

TypeError: Cannot read property 'send' of null
    at Object.5.s.send (swampdragon.min.js:1)
    at Object.5.s.sendJSON (swampdragon.min.js:1)
    at Object.5.s.callRouter (swampdragon.min.js:1)
    at Object.callRouter (services.js:9)
    at Object.create (services.js:41)
    at k.$scope.sendMessage (controllers.js:28)
    at cb.functionCall (angular.js:10795)
    at angular.js:19036
    at k.$get.k.$eval (angular.js:12632)
    at k.$get.k.$apply (angular.js:12730)

Any help would be awesome, I love this framework and I am going to be using it on my latest project.

**Comment by jonashagstedt** [comment]
Have you started the swampdragon server `./manage.py runsd`?
It looks like the socket has gone walkabout

**Comment by xxxkilldogxxx** [comment]
I have a production setup and a local setup (still using the VPS Redis/SwampDragon thought)

Its all behind NGINX using this config:

upstream swampdragon {
        server 127.0.0.1:9000;
}

server {
        listen 80;
        server_name app.csgodraw.net;

       # WebSocket.
       location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_set_header Host $http_host;
          proxy_pass http://swampdragon;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
       }
}

The Django portion is similar with a proxy pass but in another server directive for the main domain.

The settings I have in Django are these:

SWAMP_DRAGON_CONNECTION = ('swampdragon_auth.socketconnection.HttpDataConnection', '/data')
SESSION_COOKIE_DOMAIN = '.csgodraw.net'
DRAGON_URL = 'http://app.csgodraw.net/'
SWAMP_DRAGON_REDIS_HOST = '45.55.73.99'

And redis is running with remote connections open on standard port, I also have Both SwampDragon and Gunicorn running via Supervisor with these settings:

Supervisor config:

[program:csgodraw]
command = /home/csgodraw/bin/gunicorn_start                    ; Command to start app
user = csgodraw                                                          ; User to run as
stdout_logfile = /home/csgodraw/logs/gunicorn_supervisor.log   ; Where to write log messages
redirect_stderr = true                                                ; Save stderr in the same log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8                       ; Set UTF-8 as default encoding

[program:swampdragon]
command=/home/csgodraw/bin/python /home/csgodraw/CSGODraw/server.py 127.0.0.1:9000
user=csgodraw
autostart=true
autorestart=true
stderr_logfile=/home/csgodraw/logs/sd.log
stdout_logfile=/home/csgodraw/logs/sd.log
stopsignal=INT
#process_name=%(program_name)s_%(process_num)01d
#numprocs=2

And the server.py is this:

#!/usr/bin/env python
import os
import sys


from swampdragon.swampdragon_server import run_server

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "CSGODraw.settings")

host_port = sys.argv[1] if len(sys.argv) > 1 else None

run_server(host_port=host_port)

I have also added you on Skype, be cool to talk to you regarding developement ect and hear how you work. I don't generally get to speak with other Python/Django developers as I find we are very few in numbers in the UK.

**Comment by jonashagstedt** [comment]
Do you have any error messages in the SwampDragon logs?

**Comment by xxxkilldogxxx** [comment]
This is all I have in my logs for SwampDragon:

    -------- SwampDragon ------
    Running SwampDragon on 127.0.0.1:9000
    DRAGON_URL: http://app.csgodraw.net/
    Version 0.4.2.2
    Debug: True
    Quit the server with ctrl+c
    ---------------------------
    DEBUG 2015-06-23 19:43:43,997 base 5336 140230834833152 Configuring    Raven for host:  http://e61148dfc4784f709eae66d7565eda03:d29550fc448946e78f851699e6c789df@sentry.minecraftmarket.com:/2
    DEBUG 2015-06-23 19:43:44,077 base 5336 140230834833152 Sending     message of length 596 to http://sentry.minecraftmarket.com/api/2/store/
    DEBUG 2015-06-23 19:44:14,572 base 5336 140230834833152 Sending message of length 596 to http://sentry.minecraftmarket.com/api/2/store/
    DEBUG 2015-06-23 19:44:56,426 base 5336 140230834833152 Sending message of length 596 to http://sentry.minecraftmarket.com/api/2/store/
    DEBUG 2015-06-23 20:51:17,661 base 5336 140230834833152 Sending message of length 592 to http://sentry.minecraftmarket.com/api/2/store/
    DEBUG 2015-06-23 20:54:03,366 base 5336 140230834833152 Sending message of length 596 to http://sentry.minecraftmarket.com/api/2/store/

The debug messages are just my log.warnings("") in the routers that I was using to help find any evidence of why it would not be working.

**Comment by jonashagstedt** [comment]
Could you share your router code?

I checked the url csgodraw.net and in the console I can access the swampdragon object without an issues (though I can not confirm if it's truly working).

**Comment by xxxkilldogxxx** [comment]
here is my router:

    from swampdragon import route_handler
    from swampdragon.route_handler import ModelRouter
    from chat.models import Messages
    from chat.serializers import MessageSerializer, UserSerializer
    from django.contrib.auth.decorators import login_required
    from accounts.models import User
    import logging

    log = logging.getLogger(__name__)

    class MessageRouter(ModelRouter):

        route_name = 'message-route'
        serializer_class = MessageSerializer
        model = Messages
        include_related = [UserSerializer,]

        def get_initial(self, verb, **kwargs):
            log.warning("GETTING INITIAL")
            user = User.objects.get(pk=kwargs['user_id'])
            print(str(user.nickname))
            return {'user': user}

        def get_object(self, **kwargs):
            return self.model.objects.get(pk=kwargs['id'])

        def get_query_set(self, **kwargs):
            return self.model.objects.all()

    route_handler.register(MessageRouter)

**Comment by jonashagstedt** [comment]
In your router, add:

    def create(self, **kwargs):
        log.warning('create was called')
        # Don't do anything else in here, we are just interested to see if this
        # is triggered at all


using Chrome or FF, in the console run:

    swampdragon.create('message-route', {message:'test'}, 
    function (e, response) { 
        console.log(response); 
    }, 
    function (e, error) {
        console.log(error);
    });


That way you can see if you get any messages in the browser console and in your log files.

**Comment by xxxkilldogxxx** [comment]
I did what you just said earlier today and got a successful log warning.

![Image of log warning for create](http://puu.sh/iAbKQ/325ee26d73.png)

**Comment by jonashagstedt** [comment]
Running this in the console: 

    swampdragon.getList("message-route", {}, function (e, response) { console.log(response); })

does output a response.

I suspect this is an issue with your Redis server

**Comment by xxxkilldogxxx** [comment]
Would you have any idea where I should start looking... because it seems to be working partially and when I override the create function.

Also weirdly last night when I was trying all different tests I manage to get it working before i went sleep  and I was getting a object response back saying "this field cannot be null" but I cant reproduce that today.

**Comment by jonashagstedt** [comment]
It looks like the server <-> client stuff is working, but publishing messages do not.

make sure you can connect to Redis from your swampdragon server using `redis-cli` along with the same Redis settings as you use in your settings file.

You need Redis 2.8 or higher if I remember correctly, before that pubsub wasn't available.

If it works to connect with your redis-cli you can run `PUBSUB channels *` in the redis client and it should show any active connections.

**Comment by xxxkilldogxxx** [comment]
I don't have any settings regarding Redis in my settings.py at all, and redis is running on 127.0.0.1:6379 and also the public IP for testing currently

I get this back from redis-cli INFO:

    # Server
   redis_version:2.8.17
   redis_git_sha1:00000000
   redis_git_dirty:0
   redis_build_id:5937320cdd80c1e4
   redis_mode:standalone
   os:Linux 3.16.0-4-amd64 x86_64
   arch_bits:64
   multiplexing_api:epoll
   gcc_version:4.9.2
   process_id:5527
   run_id:8cceb0d1a914d2a7ea0c0aaf8718bc8c3dd347cc
   tcp_port:6379
   uptime_in_seconds:419
   uptime_in_days:0
   hz:10
   lru_clock:9031484
   config_file:/etc/redis/redis.conf

   # Clients
   connected_clients:1
   client_longest_output_list:0
   client_biggest_input_buf:0
   blocked_clients:0

   # Memory
   used_memory:503664
   used_memory_human:491.86K
   used_memory_rss:3207168
   used_memory_peak:503664
   used_memory_peak_human:491.86K
   used_memory_lua:33792
   mem_fragmentation_ratio:6.37
   mem_allocator:jemalloc-3.6.0

   # Persistence
   loading:0
   rdb_changes_since_last_save:0
   rdb_bgsave_in_progress:0
   rdb_last_save_time:1435094425
   rdb_last_bgsave_status:ok
   rdb_last_bgsave_time_sec:-1
   rdb_current_bgsave_time_sec:-1
   aof_enabled:0
   aof_rewrite_in_progress:0
   aof_rewrite_scheduled:0
   aof_last_rewrite_time_sec:-1
   aof_current_rewrite_time_sec:-1
   aof_last_bgrewrite_status:ok
   aof_last_write_status:ok

   # Stats
   total_connections_received:1
   total_commands_processed:1
   instantaneous_ops_per_sec:0
   rejected_connections:0
   sync_full:0
   sync_partial_ok:0
   sync_partial_err:0
   expired_keys:0
   evicted_keys:0
   keyspace_hits:0
   keyspace_misses:0
   pubsub_channels:0
   pubsub_patterns:0
   latest_fork_usec:0

   # Replication
   role:master
   connected_slaves:0
   master_repl_offset:0
   repl_backlog_active:0
   repl_backlog_size:1048576
   repl_backlog_first_byte_offset:0
   repl_backlog_histlen:0

   # CPU
   used_cpu_sys:0.36
   used_cpu_user:0.16
   used_cpu_sys_children:0.00
   used_cpu_user_children:0.00

And as for PUBSUB channels *:

    127.0.0.1:6379> PUBSUB channels *
    (empty list or set)

**Comment by jonashagstedt** [comment]
You have this: `SWAMP_DRAGON_REDIS_HOST = '45.55.73.99'`
Remove that setting if you aren't using it.

**Comment by xxxkilldogxxx** [comment]
If i'm correct I need that on my local setup because the redis server is on the VPS but I have removed it on the production setup and tried again on the site with the same error and nothing still in the channels list.

**Comment by xxxkilldogxxx** [comment]
I have done some debugging with the redis-cli monitor and found this:

When reloading the page I get:
    csgodraw@srv1:~/CSGODraw$ redis-cli monitor
    OK
    1435095872.789143 [0 127.0.0.1:37589] "SUBSCRIBE" "messages|"
    1435095872.790802 [0 127.0.0.1:37589] "SUBSCRIBE" "user|"

Then when clicking the input box which triggers the sendMessage():

    1435095879.758190 [0 127.0.0.1:37589] "UNSUBSCRIBE" "messages|"
    1435095879.758824 [0 127.0.0.1:37589] "UNSUBSCRIBE" "user|"

**Comment by xxxkilldogxxx** [comment]
I have changed everything to localhost including the swampdragon server just for testing and I am now successfully getting responses back with correct information like I should be.

I am not sure what could be different on the production server honestly apart from NGINX.

Any ideas?

Also I am using the redis server remotely so it looks like the fault is not redis after all... could NGINX bedropping the connection straight away?

**Comment by xxxkilldogxxx** [comment]
I found the issue but I don't know exactly why it caused the issue so maybe you can shed some light on it.


    def get_initial(self, verb, **kwargs):
        user = User.objects.get(pk=self.connection.user.pk)
        return {'user': user}

If I remove this function I get everything working as it should, why is this?

Also how should I pass the user to the create function? or do I have to override the create function?

**Comment by xxxkilldogxxx** [comment]
I am going to close this issue, I found the issue and the reason I couldn't find why was because my logging setup was shutting out the tornado errors... 

I feel a tad silly now.

**Comment by jonashagstedt** [comment]
Good work!

Also `user = User.objects.get(pk=self.connection.user.pk)`, why not just call `self.connection.user` ?

**Comment by xxxkilldogxxx** [comment]
I am now as you can see in the issue I cleaned it up.
