### ISSUE TITLE
@login_required Uncaught TypeError: Angular JS error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by xxxkilldogxxx** [jonashagstedt/swampdragon#111]
I am trying to add a login_required decorator to my create function and it works when logged in however when not logged in I get a error:

    Chrome: Uncaught TypeError: Cannot read property 'length' of undefined
    Firefox: 04:49:29.834 TypeError: e.remote_channels is undefined1 swampdragon.min.js:1:996

Here is my router:

    class MessageRouter(ModelRouter):

        route_name = 'message-route'
        serializer_class = MessageSerializer
        model = Messages
        include_related = [UserSerializer]

        def get_initial(self, verb, **kwargs):
            return {'user': self.connection.user}

        @login_required
        def create(self, **kwargs):
            return super(ModelRouter, self).create(**kwargs)

        def get_object(self, **kwargs):
            return self.model.objects.get(pk=kwargs['id'])

        def get_query_set(self):
            return self.model.objects.all()

    route_handler.register(MessageRouter)

However I can do:

    self.send({test:'test'})

And I receive it in the client no problem, which I find very odd. Am I missing something here?

**Comment by jonashagstedt** [comment]
Are you getting any Python errors?

**Comment by xxxkilldogxxx** [comment]
No Python errors at all, the only error I am getting is on the client side and this happens if I use the decorator or self.send_login_required().

I am using Django 1.8.2 
Swampdragon 4.3
Swampdragon auth

**Comment by jonashagstedt** [comment]
Try removing the login required decorator and after `include_related` add this line:

`permission_classes = [LoginRequired('create')]`

**Comment by xxxkilldogxxx** [comment]
That somewhat worked, however I am getting no response back in the console even though I am catching everything.

**Comment by jonashagstedt** [comment]
Does all this work on your local dev machine?

**Comment by xxxkilldogxxx** [comment]
I havnt pushed the updates to the production yet but I can if you want?

**Comment by jonashagstedt** [comment]
If it doesn't work on your local machine it should be easy to find the issue through the magic of `ipdb`.

If you are not familiar with `ipdb` I strongly recommend it:
https://docs.google.com/presentation/d/1c6BaV6T57z8UjkEd32xQErMtLT0fC-mZOCRaCcP7dcs/edit#slide=id.p

**Comment by xxxkilldogxxx** [comment]
Okay I will take a look with ipdb and see what I can come up with, thank you for the fast support btw.

**Comment by xxxkilldogxxx** [comment]
Not really sure what I am doing wit ipdb honestly, but if I put it just before the MessageRouter class and keep pressing n eventually I get:

    ipdb> n
    ipdb> n
    --Return--
    ipdb> n
    ipdb> n
    --Return--
    ipdb> n
    ipdb> n
    ipdb> n
    ipdb> n
    ipdb> n
    ipdb> n
    ipdb> n
    ImportError: 'No module named routers'
    ipdb> n

If I place ipdb above the login_required decorator I get nothing, can you guide me a little?

**Comment by xxxkilldogxxx** [comment]
def send_login_required(self, channel_setup=None):
        print("SENDING LOGIN REQUIRED")
        print(channel_setup)
        self.context['state'] = LOGIN_REQUIRED
        self.connection.send(format_message(data=None, context=self.context, channel_setup=channel_setup))

Where I am printing the channel_setup I am getting this:

    {'signin_required': 'you need to sign in'}

Where on a regular send channel_setup would be something like this?
    {'local_channel': u'messages', 'action': 'subscribe', 'remote_channels': ['messages|', 'user|']}

Does this help at all?

**Comment by jonashagstedt** [comment]
that message should end up on the client side, you should be able to check for that message and if you get that you can prompt the user to sign in.

**Comment by xxxkilldogxxx** [comment]
$scope.sendMessage = function() {
        console.log("TESTING");
        $dragon.create('message-route', $scope.messageData).then(function(response) {
            console.log(response.data);
        }).catch(function(errors) {
            console.log(errors);
        });
    }

Is what I have on the receiving end and all I am getting is:

    Uncaught TypeError: Cannot read property 'length' of undefined

Is that because of my code? or the swampdragon.js because thats where it says the issue is.

**Comment by xxxkilldogxxx** [comment]
Are you able to reproduce this error and would you like me to push it to the VPS so you can see it for your self?

**Comment by jonashagstedt** [comment]
Do you get this error if you login before you try to create a message?

**Comment by xxxkilldogxxx** [comment]
If I login and send a message I get this response:

!['Working correctly message'](http://puu.sh/iBdK7/1e2778634b.png)

However when not logged in and I try and send a message I get:

    Uncaught TypeError: Cannot read property 'length' of undefined

Which leads me to this function: 

    function setupChannels(channelSetup) {
        var remoteChannels = channelSetup.remote_channels || [],
            remoteChannelCount = channelSetup.remote_channels.length,
            i;

Which is line 35 in swampdragon.js I changed to non minified for the sake of finding the function easier.

**Comment by jonashagstedt** [comment]
Okay I think I have the whole picture.

You need to inspect the incoming data in JavaScript.
When you receive a message with login_required you should disabled the interface until the user has signed in.
Easiest would be to simply redirect the user to the login page.

You could also put the entire page behind login.

**Comment by xxxkilldogxxx** [comment]
Wouldn't I be able to see the login_required in the response to sendMessage() though? or do I need to catch login_required in the onchannelmessages? 

Little bit confused here...

**Comment by xxxkilldogxxx** [comment]
So from inspecting the websocket I am getting this back:

    a[{"channel_data":{"signin_required":"you need to sign in"},"data":null,"context":{"client_callback_name":"cb_3","state":"login_required","verb":"create"}}]

So I need to handle this in my javascript then?

**Comment by jonashagstedt** [comment]
Whoa! no that is totally bananas.
That shouldn't even happen!

Which version of SD are you using? 

Try ditching the Angular service and use this one instead:
https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/dist/swampdragon.js

(docs here: http://swampdragon.net/documentation/javascript/)

**Comment by xxxkilldogxxx** [comment]
So I am not going totally mental then after all? 

I was using 4.2.2 and last night I switch to 4.3 as I noticed you mate some changes to remote channels.

And okay i'll give it a try later tonight as I have to pop out for a moment, I really want to use this on our new project and especially with angular because I can see great potential.

Would it not be easier to figuire this out over skype?

**Comment by jonashagstedt** [comment]
I have too much work to focus this much on one issues (I haven't reviewed all the PRs yet even).

Angular support is probably going to be deprecated at some point as well, with more focus on the vanilla version as I don't use Angular my self and I don't have any time to maintain it.

I still have tons of client work to finish so I'm afraid I'm going to have to leave this issue for now, but I suspect the vanilla version won't give you this grief. 
If however it does do log an issue about it.

**Comment by xxxkilldogxxx** [comment]
Okay no problem I will see how it goes.

**Comment by xxxkilldogxxx** [comment]
Okay I have done some digging and found this:

    def send_login_required(self, channel_setup=None):
        self.context['state'] = LOGIN_REQUIRED
        self.connection.send(format_message(data=None, context=self.context, channel_setup=channel_setup))

This is the response I get back with the current function:

    a[{"channel_data":{"signin_required":"you need to sign in"},"data":null,"context":{"client_callback_name":"cb_2","state":"login_required","verb":"create"}}]

All the other send functions have data however this one does not and there for set data to None, however the @login_required sends data as the first argument which then because of the lack of data in this function get set into channel data.

So I have done this:

    def send_login_required(self, data, channel_setup=None):
        self.context['state'] = LOGIN_REQUIRED
        self.connection.send(format_message(data=data, context=self.context, channel_setup=channel_setup))

This is the websocket message I get back with my changes:

    a[{"data":{"signin_required":"you need to sign in"},"context":{"client_callback_name":"cb_2","state":"login_required","verb":"create"}}]

And now I don't get any errors but I dont get any response either in my javascript but I believe thats because it does not know how to handle it yet.

I know you don't have time for this issue however is this what I should expect? if so should I make a pull request?

**Comment by xxxkilldogxxx** [comment]
Just a confirmation would be great if
Possible

**Comment by xxxkilldogxxx** [comment]
The reason why the login_required decorator is failing is because of the context "state".

Swampdragon.js can only handle Success and Error yet the send_login_required function sets the context state to LOGIN_REQUIRED.

How should this be handled?

**Comment by xxxkilldogxxx** [comment]
I don't believe this is actually a angularJS issue as the swampdragon.js file does not know how to handle the state of LOGIN_REQUIRED.

swampdragon.callRouter = function (verb, route, args, success, failure, channel) {
    var callbackName = eventHandler.getCallbackName();
    if (channel != null) {
        args = args || {};
        args.channel = channel;
    }

    eventHandler.on(callbackName, function (context, data) {
        if (context.state == 'success') {
            if (success) { success(context, data)}
        }
        if (context.state == 'error') {
            if (failure) { failure(context, data)}
        }
    });

This is a bug right?

**Comment by jonashagstedt** [comment]
I'm considering wether to allow for custom states and state handlers.

Currently there are two states, `SUCCESS` and `ERROR`.
Either allow for custom states or make login_required an error.

So wether it's a bug or a missing feature is the question.

**Comment by xxxkilldogxxx** [comment]
Custom states would be pretty good idea and would future proof permissions in a way as I was thinking of passing a login url with the LOGIN_REQUIRED state.

I think its a bug currently but would be better off being a missing feature.

**Comment by jonashagstedt** [comment]
It's too soon to say really.

However for now, I would recommend simply putting the page behind a login.
That way you won't have to handle the actual permission, however do retain the permission for security reasons.

I'm closing this issue with the conclusion: put entire page behind login for now.

**Comment by xxxkilldogxxx** [comment]
Putting the page behind login is not a solution due to the chat being viewable by anon users as well.

I'll just go ahead and edit SD and find a solution, if I find my self using permissions a lot i'll see if I can create a system for handling custom states ect.
