### ISSUE TITLE
Cant override save() function.

### ISSUE THREAD

**Issue by xxxkilldogxxx** [jonashagstedt/swampdragon#113]
If you override the save() function in a model to update a field you trigger not only the create pub but also a update pub due to SelfPublishModel.__init__() grabbing all field data before the overriding save method is called making the SelfPublishModel.save() think a update has happened.

While this is fairly annoying on its own what also gets very annoying is along with this my user foreign_key field in my model will no longer return a user object like it did before due to me overriding the save method all because I am updating a field.

I have done a lot of debugging, infact hours of debugging so a moment of your time to help solve this would be greatly appreciated so we can fix this and then my team can move on with our project.

**Comment by jonashagstedt** [comment]
The title is misleading.
You **can** override the save function, there is no syntax error with overriding the save function and there is no bug with overriding the save function, it's a question of what you do with it.

Without seeing the code where you override the save function I can't but guess what the actual problem is.

Perhaps the self publishing model is not right in this case and you should publish the model manually?

**Comment by xxxkilldogxxx** [comment]
class Messages(SelfPublishModel, models.Model):
        serializer_class = MessageSerializer
        user = models.ForeignKey(User)
        message = models.CharField(max_length=100)
        sent = models.DateTimeField(default=timezone.now(), blank=True, null=True)
        edited = models.DateTimeField(blank=True, null=True)

        def save(self, *args, **kwargs):
            self.edited = timezone.now()
            return super(Messages, self).save(*args, **kwargs)

**Comment by jonashagstedt** [comment]
That would be an issue.
I think you simply have to remove the `SelfPublishModel` part from the message model.

Have a look at http://swampdragon.net/documentation/routers-base-model-publisher-router/
It's a router that handles publishing, see if that is of any help.

**Comment by xxxkilldogxxx** [comment]
Ahh okay.

I did try editing the SelfPublishModel class to find a way to make it work but nothing seemed to work to fix it.

Will you be taking a look at this issue at some point?

**Comment by jonashagstedt** [comment]
Yes I do believe it should be a possibility to override the save function. 
I'm going to open a new issue around this but it will most likely not make it into the 0.4.3 version.
Closing this one for now in favour of a new issue
