### ISSUE TITLE
Password hash being sent to client on call back

### ISSUE THREAD

**Issue by tawanda** [jonashagstedt/swampdragon#116]
This is my serializer
```
class UserSocketSerializer(ModelSerializer):
    class Meta:
        model = 'accounts.User'
        publish_fields = ('email', 'first_name', 'last_name', 'company', 'is_admin', 'is_staff')
        update_fields = ('email', 'first_name', 'last_name', 'is_admin', 'is_staff', 'password', 'is_staff',
                         'user_is_active', 'company', 'use_as_company',)
```
Client sends new password 
```
["{\"route\":\"user\",\"verb\":\"update\",\"args\":{\"password\":\"aaaaaaa\",\"id\":76},\"callbackname\":\"cb_6\"}"]
```
server responds with publish_fields (without the password ) as expected
```
a[{"context":{"verb":"update","state":"success","client_callback_name":"cb_6"},"data":{"first_name":"saefsadfas","_type":"user","last_name":"sdfsdf", "email":"afsdf@afsdf.sdafd"}}]
```
but then the next thing the server sends by itself is what field was updated in this case the password hash
```
a["{\"channel\": \"user|company_id:1\", \"action\": \"updated\", \"data\": {\"id\": 76, \"_type\": \"user\", \"password\": \"pbkdf2_sha256$20000$hT0oibssIP3v$g3uO+8aq/o9IMcD7u+zLzNI7s7s5B3MOf23gEH0C8GE=\"}}"]	
```
This is not what we want. how do we get swamp dragon to not send this field hashed or not

**Comment by jonashagstedt** [comment]
Don't include the password in the update fields.
publish fields and update fields is data that the client is allowed to read / write.

Instead, create a method on your router:

    def change_password(self, new_password):
        user = get_your_user()
        user.set_password(new_password)
        self.send({'message': 'password changed'})

and add `change_password` to `allowed_verbs`

then you can call this with:

    swampdragon.callVerb('change_password', 'your-router', {new_password: 'some-password'});

**Comment by tawanda** [comment]
Thank you
