### ISSUE TITLE
<Point object at XXXX> is not JSON serializable

### ISSUE THREAD

**Issue by Eon1** [jonashagstedt/swampdragon#158]
Trying to do a self publishing model. I get this error whenever saving a model that has PointField. I'm using Postgresql with all the spatial features and utilizing spatial queries in django. So i need PointFields. The same model will serialize no problem using django rest framework so i know it's possible to serialize in Json.

**Comment by jonashagstedt** [comment]
Override the field in the serializer.

	class FooSerializer(ModelSerializer):
	    class Meta:
	        model = Foo

	    def serialize_poingfield(self, obj):
	        return str(obj.pointfield)  # Or however you want to format it

**Comment by Eon1** [comment]
That didn't work I get the same error. I put that in my dragonserializer file. I'm not really sure what it wants returned ? the output of obj.pointfield looks like this SRID=3857;POINT (-11897260.2044618280000000 4108821.7579158251000000) (that's a random spot near the middle of usa). I am able to serialize the entire model like this jsonmodel = serializers.serialize("json", [obj]) without issue. but no matter what I return it gives me this error.

**Comment by Eon1** [comment]
never mind disregard that last comment i had a typo in my def name :) works great thanks !
