### ISSUE TITLE
is there a repo for the documentation?

### ISSUE THREAD

**Issue by rwillmer** [jonashagstedt/swampdragon#16]
There's a few typos, etc in the documentation. I was going to send you a PR to fix them but it looks like the doco has moved out of this repo.

**Comment by jonashagstedt** [comment]
Yes the docs are hosted on swampdragon.net now.
If you remember any obvious ones feel free to point them out and I'll update them.

Cheers

**Comment by jonashagstedt** [comment]
Closing this issue for now but feel free to point out any typos. 
I'll look through the docs next time I update it
