### ISSUE TITLE
Settings.js

### ISSUE THREAD

**Issue by n0nama** [jonashagstedt/swampdragon#190]
Good day!
I have a problem with a first tutorial. I read in docs "If you have been reading the documentation you might have noticed the new settings.js that contains the url, endpoints and user defined settings."
What is a settings.js and where I can find this file?

**Comment by AlexejStukov** [comment]
This file should be provided by your swampdragon instance under your ```DRAGON_URL/settings.js```. You cannot edit it directly. It is just there for swampdragon to use.

**Comment by n0nama** [comment]
Thanks, Alexej. Actually, I found solution in closed issues. Definitely can close this issue.

**Comment by AlexejStukov** [comment]
No problem. I can't close it, but you should be able to do that.
