### ISSUE TITLE
Release version does not work with Django1.9

### ISSUE THREAD

**Issue by daavve** [jonashagstedt/swampdragon#200]
Hi,

I currently maintain the [python-django-swampdragon](https://aur.archlinux.org/packages/python-django-swampdragon/) package for Arch Linux:

Unfortunately the current version available through pip [swampdragon-0.4.2.2](https://pypi.python.org/pypi/SwampDragon) is well behind the development branch does not work out-of-the-box with Django version 1.9 and later.

I've managed to get the pip version working by building a bunch of patches I ported from the development branch.

Please do a point release.

Thanks,

-Dave

**Comment by mback2k** [comment]
@jonashagstedt It would be nice if you could do a point release with the fixes for Django 1.9 and those that are already in the 0.4.3 branch, especially issue #67. Thanks!

**Comment by ZuSe** [comment]
@mback2k 
i think jonas has only very limited time at the moment. From what I see you are very much into the architecture. If jonas agrees i would suggest to make you official contributor of the project, just do then what you are able to do.

**Comment by daavve** [comment]
Hi again,

Unfortunately I've found that SwampDragon does not meet my needs.  I have stopped maintaining the AUR package python-django-swampdragon](https://aur.archlinux.org/packages/python-django-swampdragon/)  for Arch Linux.  If someone out there uses Arch Linux please consider adopting it.

-Dave
