### ISSUE TITLE
settings.js not found

### ISSUE THREAD

**Issue by SparksFyz** [jonashagstedt/swampdragon#203]
swampdragon 0.4.2.2 django 1.8.1  

 I am a newbie and when I run the chat example, some errors occurred. 
 
I have both tried `manage.py runsd`  and `manage.py runserver 0.0.0.0:9999`

when I used runserver, here are the errors in web page.
![screenshot from 2016-03-11 19 34 28](https://cloud.githubusercontent.com/assets/8748814/13701097/6ba74f90-e7c0-11e5-9b82-ec03b6bfe524.png)

when I used runsd, the errors in terminal like this:
![screenshot from 2016-03-11 19 40 59](https://cloud.githubusercontent.com/assets/8748814/13701203/3714a9f2-e7c1-11e5-8dc1-38088dc856cc.png)

I think it maybe about the `settings.py`, but I have not changed any settings or files in templates.

I hope someone can help me. Thanks~

**Comment by oraac** [comment]
The problem has to do with swampdragon/templatetags/swampdragon_tags.py, and it is present in the release version.

You'll have to either install the development version or patch the release version.

I maintain the Arch Linux package of swampdragon [here](https://aur.archlinux.org/packages/python-django-swampdragon/) I've backported many fixes from the development release as patches.

If you want to patch for your particular issue, I've attached a diff you can reference.  You would probably be easier for you to install the development version though.

Please let me know if you have questions.

-Dave
[diff.txt](https://github.com/jonashagstedt/swampdragon/files/170009/diff.txt)

**Comment by SparksFyz** [comment]
@oraac  Thanks for help. I have solved my problem.
