### ISSUE TITLE
Update settings documentation

### ISSUE THREAD

**Issue by argaen** [jonashagstedt/swampdragon#23]
SWAMP_DRAGON_HOST and SWAMP_DRAGON_PORT are missing in the [settings doc](http://swampdragon.net/documentation/settings/) section.

Btw: I think it would be better to have a repo for the docs as asked for in #16. I think that allowing to make pull requests and all this stuff would be easier than opening an issue for every typo/thing we find =).

**Comment by jonashagstedt** [comment]
It's on it's way.
I'm currently updating the main website and in that process I will make the docs available in Markdown format in the main repo.
