### ISSUE TITLE
Update old docs

### ISSUE THREAD

**Issue by potar** [jonashagstedt/swampdragon#27]
Hi! I very appreciate the work you've done, especially your explanations, related to different issues that people submits. A lot of useful information can be found there.

It seems to me that I've found the out-of-date docs. Please check it:
https://github.com/jonashagstedt/swampdragon/blame/master/docs/routers/base-model-publisher-router.md#L18
So, there is no 'ModelPublisherRouter' inside the package as of now. Maybe you renamed those class to 'ModelPubRouter' (https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/route_handler.py#L311)

**Comment by jonashagstedt** [comment]
Good spot! 
I'll fix this right away
