### ISSUE TITLE
swampdragon.ready functions re-executing after dropped connection is reestablished

### ISSUE THREAD

**Issue by griphiam** [jonashagstedt/swampdragon#29]
functions passed to the sampdragon.ready function end up being bound the the connection's 'open' signal.  If the connection is lost and then restablished, all those functions are still bound to the 'open' signal and are called again.  For subscribe methods, it makes sense to call the subscribe again to reestablish the link.

However all callRouter calls are called again (even non-subscribe) and they shouldn't be because they were probably a call once sort of method.

Would it make sense to have two different flavors of a ready function (one that should be called again if the connection is lost and regained) and another that deregisters the callback once it's been called?

**Comment by jonashagstedt** [comment]
I see what you mean. If you end up wrapping writing calls in the `ready` call and they are being called twice, that would be bad.

One option would be to have an `onReconnect` function instead, and everything in `ready` will only be executed once.

**Comment by griphiam** [comment]
Agreed.  Both behaviors are needed (subscribes should reconnect) and most everything else would be once.

Something like:

    swampdragon.onConnect(function(){ ...put subscribes here...});
    
    swampdragon.ready(function(){ ...calls that shouldn't be called again on a disconnect/reconnect cycle ... });

**Comment by jonashagstedt** [comment]
That makes sense.

I'll note this down here so I can pick off this list:

*  Implement `onConnect`
*  `ready` should only execute once
*  document `onConnect` 
*  mention "execute once" in documentation for `ready`

**Comment by jonashagstedt** [comment]
Slight change as I came across a few things digging in to the code and saw some room for improvement:

There are two new functions:

`open`: will execute every time the connection is opened (good place for subscribe calls)
`close`: will execute every time the connection is closed (good place to disable user inputs etc)

`ready` will only trigger once, despite the connection going up and down.
