### ISSUE TITLE
Question: SD+ uWSGI

### ISSUE THREAD

**Issue by potar** [jonashagstedt/swampdragon#30]
Hi @jonashagstedt ! 

I noticed in the documentation of uWSGI that it supports the tornado loop engine (https://uwsgi-docs.readthedocs.org/en/latest/Tornado.html). Also, I see in the docs that you recommend uWSGI - http://swampdragon.net/blog/deploying-swampdragon/ for the main django application.

The question is if you have any recommendations/caveats of running SD through uWSGI.

**Comment by jonashagstedt** [comment]
I don't think I've actually tried it.

If you do try it, feel free to let me know the outcome.

I run it as per the blog post you mentioned and I've had no issues what so ever.

**Comment by potar** [comment]
ok, thanks

**Comment by ZuSe** [comment]
Any news on this topic?

I think supervisord is very kind, but it still lacks on support for python 3 in the current stable release (I know, it's coming). Furthermore using it means one more component in the landscape to be managed. I am running django with uwsgi in a mesos cluster, so it would be nice to integrate sd/tornado into the existing environment without relying on supervisor. 

Potar, have you made any progress on this topic or do I need to start from scratch?

**Comment by potar** [comment]
@ZuSe you need to start from scratch because I haven't made any progress on this topic yet.
