### ISSUE TITLE
Related Models

### ISSUE THREAD

**Issue by winkelchri** [jonashagstedt/swampdragon#31]
# Related Models

Hello,

I'm trying to figure out, how I could update the Foreign Model when I'm changing data at the base-model.

Currently I have two Models:
 - Media
 - Thumbnail

## Models
The Thumbnail has a ForeignKey field to the Media-Model. The code looks like this:

```python
class Media(SelfPublishModel, models.Model):
    serializer_class = MediaSerializer

    file = models.FileField(...)


class Thumbnail(SelfPublishModel, models.Model):
    serializer_class = ThumbnailSerializer

    media = models.ForeignKey(MediaFile)
    image = models.ImageField()

```

## Controller
Now, at the Webinterface, I would like to subscribe to all Changes according to the Media-Models (using Angular) like so:

```javascript
var MediaControllers = angular.module('MediaControllers', []);

MediaControllers.controller('MediaCtrl',
    ['$scope', '$dragon', function ($scope, $dragon) {

    $scope.mediaItems = [];
    $scope.router = 'media-router';
    $scope.channel = 'media';

    $dragon.onReady(function() {

        // Subscribe media-file
        $dragon.subscribe($scope.router, $scope.channel, {})
            .then(function(response) {
                $scope.dataMapper = new DataMapper(response.data);
            }
        );

        // Request all media_files when script is loaded
        $dragon.getList($scope.router, {}).then(function(response) {
            $scope.mediaItems = response.data;
        });

    });

    $dragon.onChannelMessage(function(channels, message) {
        // Channel-Message for media (channel)
        if (indexOf.call(channels, $scope.channel) > -1) {
            $scope.$apply(function() {
                $scope.dataMapper.mapData($scope.mediaItems, message);
            });
        }
    });
}]);
```

## Serializers
The Serializers look like:

```python
class MediaSerializer(ModelSerializer):
    thumbnail_set = ThumbnailSerializer

    class Meta:
        model = 'media.Media'
        publish_fields = [
            'file',
            'thumbnail_set',
        ]

class ThumbnailSerializer(ModelSerializer):
    class Meta:
        model = 'thumbnails.Thumbnail'
        publish_fields = [
            'image',
        ]

```

## Routers
And finally the Routers:

```python
class MediaRouter(ModelRouter):
    route_name = 'media-router'
    serializer_class = MediaSerializer
    model = MediaFile

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])

    def get_query_set(self, **kwargs):
        return self.model.objects.all()


class ThumbnailRouter(ModelRouter):
    route_name = 'thumbnail-router'
    serializer_class = ThumbnailSerializer
    model = Thumbnail

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])

    def get_query_set(self, **kwargs):
        return self.model.objects.all()
```

## Celery Task
Because it's not complex enough, I'm creating the Thumbnails in a celery-Task in order to avoid blocking the Media creation with the Thumbnail creation process.

The Task looks like:

```python
@app.task
def make_thumbnail(thumbnail_model):
    media_file = thumbnail_model.media.file

    if path.isfile(media_file.path):
        name, _ = path.splitext(path.basename(media_file.path))

        if not path.exists(thumbnail_model.filesystem_path):
            os.makedirs(thumbnail_model.filesystem_path)

        thumbnail_name = "{name}_{size}x{size}_thumbnail.{extension}".format(
            name=name,
            size=thumbnail_model.size,
            extension='jpeg',
        )

        tn_url = "/".join((thumbnail_model.url_path, thumbnail_name))
        tn_file = os.path.join(thumbnail_model.filesystem_path, thumbnail_name)

        # Generate and save Thumbnail image
        img = Image.open(mediafile_file.path)
        img.thumbnail((thumbnail_model.size, thumbnail_model.size))
        img.save(tn_file, 'JPEG')
        img.close()

        # Save thumbnail model
        thumbnail_model.image = tn_file
        thumbnail_model.save()
```

## The Problem
Now - finally - the problem. If I'm creating and changing Media-Models, all works like charm. But if I'm creating new Thumbnail-Models, the Webinterface does not receive any update messages.

I've forced this by calling in the celery-task. Now the Webinterface got an Update, every time a thumbnail was created.

```python
thumbnail_model.media_file.save()
```

### Gotten Javascript Object
But this time, the Media-Object in the Webinterface has only the ID's of the thumbnail in the 'thumbnail_set' - Array. The Media-Object at the frontend now looks like this:

```javascript
{
    "_type":"media",
    "id":2349,
    "thumbnail_set":[5425,5424],
    "file": (...),
}
```

### Excpeted Javascript Object
If I'm reloading the browser, the right Media-Object appears. I guess this happens because of the `getList()` function in the `onReady()` function.

The Media-Object now looks like this:

```javascript
{
    "_type":"media",
    "id":2349,
    "thumbnail_set":[
        {"id":5424,"image":"thumbnail_name","_type":"thumbnail"},
        {"id":5425,"image":"thumbnail_name","_type":"thumbnail"},
    ],
    "file": (...),
}
```

## Thanks!
I hope that I could describe my problem clearly enough and would be very happy about your feedback.

Regards,
winkelchri

PS:
Thank you for the great project!

**Comment by jonashagstedt** [comment]
Hi.

it's late-o-clock where I am but I will give this a stab:

Try updating your `ThumbnailSerializer` to include the `MediaSerializer`.

The Media serializer knows about thumbnails but not the other way around:

    class ThumbnailSerializer(ModelSerializer):
        media = 'MediaSerializer'

        class Meta:
            model = 'thumbnails.Thumbnail'
            publish_fields = [
                'image',
                'media'
            ]


Since I don't know your paths you might have to add the app path to the serialiser as well, but try this (the single quotes around the media = 'MediaSerializer' is not a typo).

It might look like this would cause an infinite serializer loop but it won't.

The thumbnail serializer will serialize the Media serializer, and in the process tell the Media serializer not to serialize the Thumbnail serializer (instead if will poke the PK in there I believe).

Give this a spin and let me know if it works.
If not we'll try something else.

Cheers

**Comment by winkelchri** [comment]
Hello,
thanks for the fast response!

Unfortunately the behavior is the same.

```python
class MediaSerializer(ModelSerializer):
    thumbnail_set = ThumbnailSerializer

    class Meta:
        model = 'media.Media'
        publish_fields = [
            'file',
            'thumbnail_set',
        ]

class ThumbnailSerializer(ModelSerializer):
    media = 'media.MediaSerializer'

    class Meta:
        model = 'thumbnails.Thumbnail'
        publish_fields = [
            'image',
        ]

```

Any hint where to put some debug-messages to narrow the error?

Regards
winkelchri

**Comment by jonashagstedt** [comment]
Right, I finally had some time to sit down and look at your predicament properly and I believe I see the issue.

If I understand you correctly: when you create a thumbnail you want to update the media object?

Add `include_related` to your `MediaRouter`.

    class MediaRouter(ModelRouter):
        route_name = 'media-router'
        serializer_class = MediaSerializer
        model = MediaFile
        include_related = [ThumbnailSerializer, ]

        def get_object(self, **kwargs):
            return self.model.objects.get(pk=kwargs['id'])

        def get_query_set(self, **kwargs):
            return self.model.objects.all()

I admit it's a bit hidden in the documentation [here](http://swampdragon.net/documentation/routers/).

> To subscribe to a model including changes to related models use include_related.

The reason `include_related` exists is to prevent frequent but possibly redundant publish calls.

Give this a try and see if it does what you want.

**Comment by winkelchri** [comment]
Yea, I've found it during the work on the documentation :)
I have tryed it out. But now, there are Thumbnail-objects on the frontend an I have currently not figured out, how to display them correctly.

I'm currently building a Demo-project. Maybe I've made a mistake elsewhere.

**Comment by jonashagstedt** [comment]
Well and good.
I'll close this issue now as you are getting the data. Just open another one if you run into any more issues
