### ISSUE TITLE
Contributing to the Docs

### ISSUE THREAD

**Issue by winkelchri** [jonashagstedt/swampdragon#32]
Hello,
I would like to help to update the docs. Some entrys have no syntax highlighting and in some examples, there missing imports which may help to better understand the relationships between the modules.

I was starting to fork the project and edit the docs section as I realized, that the docs seems to be moved to your own server. Is the documentation on your server still based on the github data?

Regards
winkelchri

**Comment by jonashagstedt** [comment]
It is. As per a previous request I made the docs public so updates can be made.

**Comment by winkelchri** [comment]
Thanks.
