### ISSUE TITLE
GET http://localhost:9999/settings.js 404 (NOT FOUND)

### ISSUE THREAD

**Issue by cho-is** [jonashagstedt/swampdragon#35]
I can't find in the docs about this:

where is that file suppose to be and what should contain in it?

**Comment by hiepthai** [comment]
```python
SWAMP_DRAGON_HOST = '<your_swampdragon_server_ip>' # default '127.0.0.1'

SWAMP_DRAGON_PORT = '<your_swampdragon_server_port>' # default '9999'

DRAGON_URL = 'http://<your_domain>:<your_swampdragon_server_port>' # default 'http://localhost:9999'
```
This file will provide server configuration variables for frontend javascript.

More info here: http://swampdragon.net/documentation/settings/

Hope this help

**Comment by jonashagstedt** [comment]
`{% swampdragon_settings %}` will output that file.

As hiepthai said: you need to set `DRAGON_URL` in your settings, and it needs to point to your SD server.

So if you do this: `./manage.py runsd` it will start the sever on localhost:9999
This means the `DRAGON_URL` should be `http://localhost:9999/`

If you then moved this into production on say http://sd.myserver.tld (and still used port 9999) you would change `DRAGON_URL` to use sd.myserver.tld instead of localhost.

About the settings.js file:

This is not a physical file you can edit.
By default the only thing in this file is the endpoint.

If you open a debug console in your browser and type `swampdragon_settings` you will see the endpoint there.

If you want to add your own settings you can add this to your settings.py file:

    SWAMP_DRAGON = {
        'foo': 'bar'
    }

now if you enter `swampdragon_settings` in your console you will see something like this: 

    Object {foo: "bar", endpoint: "/data"}

**Comment by cho-is** [comment]
I didn't realise about `./manage.py runsd` command.

It is working now. I will try and deploy in a server. Not sure if I need to do run the swampdragon server there too. I guess I could find some answers [here](http://swampdragon.net/blog/deploying-swampdragon/)

**Comment by cho-is** [comment]
I've followed your config for supervisord as following:

```
[program:mysite_swampdragon]
command=/path/to/virtualenv/bin/python /path/to/project/manage.py socketserver 127.0.0.1:900%(process_num)01d
user=myuser
autostart=true
autorestart=true
stderr_logfile=/path/to/logfiles/sd.log
stdout_logfile=/path/to/logfiles/sd.log
stopsignal=INT
process_name=%(program_name)s_%(process_num)01d
numprocs=2
```

It seems like I am getting `Unknown command: 'socketserver'`

Any thoughts?

**Comment by jonashagstedt** [comment]
Ah I'm afraid things have moved on since I wrote that tutorial. I shall have to update it.

Change `/path/to/project/manage.py socketserver` to `/path/to/project/server.py`

**Comment by cho-is** [comment]
Oh, now it is running:
```
Running SwampDragon on 127.0.0.1:9000
Running SwampDragon on 127.0.0.1:9001
```
But I am getting `GET https://example.com:9000/settings.js net::ERR_CONNECTION_TIMED_OUT`

I am forcing ssl but I think tghat is not the case. Anyway here is my nginx site config:
```
upstream swampdragon {
    server 127.0.0.1:9000;
    server 127.0.0.1:9001;
}

upstream wsgi_server_{{ application_name }} {
  # fail_timeout=0 means we always retry an upstream even if it failed
  # to return a good HTTP response (in case the Unicorn master nukes a
  # single worker for timing out).

  server unix:{{ virtualenv_path }}/run/gunicorn.sock fail_timeout=0;
}

proxy_next_upstream off;

server {
    listen       80;
    server_name  {{ nginx_server_name }};
    rewrite     ^   https://$server_name$request_uri? permanent;
}

server {
    listen 443 ssl;
    server_name  {{ nginx_server_name }};

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    client_max_body_size 4G;

    access_log {{ nginx_access_log_file }};
    error_log {{ nginx_error_log_file }};

    location /static/ {
        alias   {{ nginx_static_dir }};
        expires 1d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias   {{ nginx_media_dir }};
    }

    location / {
        if (-f {{ virtualenv_path }}/maintenance_on.html) {
            return 503;
        }

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 
        # enable this if and only if you use HTTPS, this helps Rack
        # set the proper protocol for doing redirects:
        # proxy_set_header X-Forwarded-Proto https;
 
        # pass the Host: header from the client right along so redirects 
        # can be set properly within the Rack application
        proxy_set_header Host $http_host;
 
        # we don't want nginx trying to do something clever with
        # redirects, we set the Host: header above already.
        proxy_redirect off;
 
        # set "proxy_buffering off" *only* for Rainbows! when doing
        # Comet/long-poll stuff. It's also safe to set if you're
        # using only serving fast clients with Unicorn + nginx.
        # Otherwise you _want_ nginx to buffer responses to slow
        # clients, really.
        # proxy_buffering off;

        # Try to serve static files from nginx, no point in making an
        # *application* server like Unicorn/Rainbows! serve static files.
    
        proxy_pass http://wsgi_server_{{ application_name }};    
        
    }

    # Error pages
    error_page 500 502 504 /500.html;
    location = /500.html {
        root {{ django_dir }}/templates/;
    }

    error_page 503 /maintenance_on.html;
    location = /maintenance_on.html {
        root {{ virtualenv_path }}/;
    }
}

server {
    listen 443 ssl;
    server_name {{ nginx_server_name }};

    # WebSocket.
    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://swampdragon;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

**Comment by jonashagstedt** [comment]
What is `DRAGON_URL` set to? Do you have a url I can check out?

**Comment by cho-is** [comment]
I am afraid my client doesn't allow me to share the url yet.

I am thankful for your help. I can provide more info if you require it. 

`DRAGON_URL = 'https://mydomain.com:9000/'`

**Comment by jonashagstedt** [comment]
No problems, I know the drill.

When I looked at the output I just had to be sure you didn't actually use "example.com" ;)

On a side note: I would recommend you run SwampDragon on a subdomain rathe than using a specific port.
I've had issues with older versions of Internet Explorer, and also some office networks will probably block the port.

Your timeout might actually be just that: are you allowed to access that port through the network?

**Comment by cho-is** [comment]
I think it might be something to do with AWS. 
I have an inbound `Custom TCP Rule    TCP    9000 - 9001    0.0.0.0/0`

But is not actually opening those I think.

**Comment by jonashagstedt** [comment]
Does it work if you go on to the server and manually run `./manage.py runserver 0.0.0.0:8000`  and `./manage.py runsd 0.0.0.0:9999`  (you have to update `DRAGON_URL` again).
This way you can check that it actually works

**Comment by cho-is** [comment]
No it doesn't work. `Running SwampDragon on 0.0.0.0:9999`
and `DRAGON_URL = 'https://domain.com:9999/'`

**Comment by jonashagstedt** [comment]
Not sure, haven't used AWS before.

But Django on 8000 works, so try putting SwampDragon on 8001 or 8080 or such

**Comment by cho-is** [comment]
So I am running SP on a subdomain as you suggested and now I am getting `502 Bad Gateway`

that is obviously something to to with nginx config

**Comment by jonashagstedt** [comment]
Where are you getting the 502?
When accessing the settings?

**Comment by jonashagstedt** [comment]
Do you have something liket his in your NGINX config:

    upstream swampdragon {
        server 127.0.0.1:9000;
    }

    ...

    # SwampDragon
    server {
        listen 80;
        server_name subdomain.domain.com;

        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header Host $http_host;
            proxy_pass http://swampdragon;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

**Comment by cho-is** [comment]
Yes, accessing the settings. 

Here you have the nginx config again. Could you see something unusual?
```
upstream swampdragon {
    server 127.0.0.1:9999;
}

upstream wsgi_server_{{ application_name }} {
  # fail_timeout=0 means we always retry an upstream even if it failed
  # to return a good HTTP response (in case the Unicorn master nukes a
  # single worker for timing out).

  server unix:{{ virtualenv_path }}/run/gunicorn.sock fail_timeout=0;
}

proxy_next_upstream off;

server {
    listen       80;
    server_name  {{ nginx_server_name }};
    rewrite     ^   https://$server_name$request_uri? permanent;
}

server {
    listen 443 ssl;
    server_name  {{ nginx_server_name }};

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    client_max_body_size 4G;

    access_log {{ nginx_access_log_file }};
    error_log {{ nginx_error_log_file }};

    location /static/ {
        alias   {{ nginx_static_dir }};
        expires 1d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias   {{ nginx_media_dir }};
    }

    location / {
        if (-f {{ virtualenv_path }}/maintenance_on.html) {
            return 503;
        }

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 
        # enable this if and only if you use HTTPS, this helps Rack
        # set the proper protocol for doing redirects:
        # proxy_set_header X-Forwarded-Proto https;
 
        # pass the Host: header from the client right along so redirects 
        # can be set properly within the Rack application
        proxy_set_header Host $http_host;
 
        # we don't want nginx trying to do something clever with
        # redirects, we set the Host: header above already.
        proxy_redirect off;
 
        # set "proxy_buffering off" *only* for Rainbows! when doing
        # Comet/long-poll stuff. It's also safe to set if you're
        # using only serving fast clients with Unicorn + nginx.
        # Otherwise you _want_ nginx to buffer responses to slow
        # clients, really.
        # proxy_buffering off;

        # Try to serve static files from nginx, no point in making an
        # *application* server like Unicorn/Rainbows! serve static files.
    
        proxy_pass http://wsgi_server_{{ application_name }};    
        
    }

    # Error pages
    error_page 500 502 504 /500.html;
    location = /500.html {
        root {{ django_dir }}/templates/;
    }

    error_page 503 /maintenance_on.html;
    location = /maintenance_on.html {
        root {{ virtualenv_path }}/;
    }
}

server {
    listen 443 ssl;
    server_name sd.{{ nginx_server_name }};

    # WebSocket.
    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://swampdragon;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by jonashagstedt** [comment]
Okay can you show me the supervisor config as well (or what ever you use to start swampdragon)

**Comment by jonashagstedt** [comment]
The server section differs from mine where I have these:

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;

**Comment by cho-is** [comment]
Supervisord config

```
[program:{{ application_name }}]
command = {{ virtualenv_path }}/bin/gunicorn_start
user = {{ gunicorn_user }}
stdout_logfile = {{ application_log_dir }}/supervisord/gunicorn_supervisor.log
redirect_stderr = true

[program:{{ application_name }}_sp]
command = {{ virtualenv_path }}/bin/python {{ django_dir }}/server.py 127.0.0.1:900%(process_num)01d
user = {{ gunicorn_user }}
autostart = true
autorestart = true
stderr_logfile = {{ application_log_dir }}/supervisord/sd.log
stdout_logfile = {{ application_log_dir }}/supervisord/sd.log
stopsignal = INT
process_name = %(program_name)s_%(process_num)01d
numprocs = 2

```

**Comment by jonashagstedt** [comment]
Here is your issue:

In NGINX you have:

upstream swampdragon {
    server 127.0.0.1:9999;
}

But in supervisor you have: command = {{ virtualenv_path }}/bin/python {{ django_dir }}/server.py 127.0.0.1:900%(process_num)01d

And you have two processes as well, so you need to setup both in NGINX:

Change:

upstream swampdragon {
    server 127.0.0.1:9999;
}

to

upstream swampdragon {
    server 127.0.0.1:9000;
    server 127.0.0.1:9001;
}

**Comment by cho-is** [comment]
Right, I didn't realise it after posting it  : )

It seems like is working now but complaining about 
```
Mixed Content: The page at 'https://thedomain.com/chat/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://sd.thedomain.com/data/info'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by jonashagstedt** [comment]
If you open a JavaScript debug console and type `swampdragon_host`, what is the output?

**Comment by cho-is** [comment]
`http://sd.thedomain.com`

my `DRAGON_URL = 'https://sd.justjoinup.com/'` is actually https

**Comment by jonashagstedt** [comment]
You can add me on google talk if you want. I feel like we are getting off the original issue and I wouldn't want any of your clients data to end up here. My email is at the top of this page: http://swampdragon.net/faq/

**Comment by cho-is** [comment]
So, I still having some issues:

`WebSocket connection to 'wss://sd.domain.com/data/185/cr5qtzs5/websocket' failed: Error during WebSocket handshake: Unexpected response code: 502`

**Comment by jonashagstedt** [comment]
I haven't seen that one before I did a quick google and came up with this:

https://chrislea.com/2013/02/23/proxying-websockets-with-nginx/

> I solved this problem by adding following directives to my nginx vhost config:
>
>In the server section I’ve added following:
>
>large_client_header_buffers 8 32k;
>
>In the location section I’ve added this:
>
>proxy_buffers 8 32k;
>proxy_buffer_size 64k;

**Comment by cho-is** [comment]
Right so it seems to be working finally! Many thanks!

Took me like 3 days to set up on AWS with Ansible.  So finally I am ready to start testing around.

**Comment by jonashagstedt** [comment]
Good work! 
Did changing the client header buffers and proxy buffers work?

**Comment by cho-is** [comment]
I didn't try that, but I changed nginx config as bellow:
```
    # WebSocket.
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://swampdragon;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
