### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by voiddragon** [jonashagstedt/swampdragon#37]
Swampdragon is a little too quiet and error 3001 connection aborted isn't very helpful for debugging.

**Comment by jonashagstedt** [comment]
What would you like to see?

**Comment by voiddragon** [comment]
Hmm, 

so far I've been resorting to printing the exceptions in the sockjs connection

    def on_message(self, data):
        try:
            data = self.to_json(data)
            if data == {'heartbeat': '1'}:
                self.on_heartbeat()
                return
            handler = route_handler.get_route_handler(data['route'])
            handler(self).handle(data)
        except Exception as e:
            self.abort_connection()
            print e
            raise e

**Comment by jonashagstedt** [comment]
If an error is raised in `on_message` you shouldn't have to print it unless you are muting them somewhere. They are already printed.

Could you give me an example of something that doesn't show an error message for you where you are required to print it out?

**Comment by voiddragon** [comment]
```
class AppRouter(ModelRouter):
    route_name = 'appimage-route'
    serializer_class = AppSerializer
    model = App

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])

    def get_query_set(self, **kwargs):
        return self.model.objects.all()
```

While following the example on the documentation, I kept getting 3001 connection aborted as the websocket reply. After added the print debug which gave a very cryptic 'id', i swapped it to 

```
    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['pk'])
```

On the front end I was attempting a subscribe and was quite puzzled by connection aborted and no other errors on my terminal.

**Comment by jonashagstedt** [comment]
I've added this line `return self.model.objects.get(pk=kwargs['id'])` and tried it out and I'm getting the exact error in the terminal I should get:


    line 14, in get_object
        return self.model.objects.get(pk=kwargs['id'])
    KeyError: 'id'

Trying to access a key that does not exist in a dict.

What version of sd are you using? 
I'm surprised you don't see any errors as I clearly see them.

**Comment by voiddragon** [comment]
I think I'm running a fairly old version, I'll update and try again.

SwampDragon 0.4.0.2

**Comment by jonashagstedt** [comment]
Instead of running it within an ide try running it from a terminal.

So from a terminal run `./manage.py runsd`.

**Comment by CptLemming** [comment]
I'd been having the same problem, no errors in the console and a `3001 connection aborted` error on the client (running as a management command or from IDE did not help in my case).

After a little digging I found that SockJS uses python logging, but you need to add a log handler for Django to pick up on this. My log handler looks like this:

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'tornado.general': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        }
    }
}
```

I can now see a stacktrace and error message in the console.

**Comment by voiddragon** [comment]
Ahh thanks, my other dev also had the same problem.

**Comment by jonashagstedt** [comment]
I would like to be able to replicate this but I haven't been able to so far.
I haven't seen this yet and never had to do anything to `LOGGING` in settings.

What version of Django are you running?
Any particular packages installed that has to do with logging etc.?

Also, good work for solving this @CptLemming

**Comment by voiddragon** [comment]
Django 1.7.4

Hmm, maybe sentry would be causing this? But I'm not getting error logs forwarded to sentry that are swampdragon related.

Actually it would be nice to be able to forward the swampdragon error logs to sentry,
