### ISSUE TITLE
Swampdragon over HTTPS

### ISSUE THREAD

**Issue by Mortymus** [jonashagstedt/swampdragon#38]
Hi,

I need to serve my application over HTTPS and I had some trouble getting the correct protocol into the `window.swampdragon_host` variable which is returned by the swampdragon javascript settings file.

I am using nginx as the webserver and configured it as described in the official blog post about deployment. Additionally I configured it to use SSL:

```
upstream swampdragon {
    server 127.0.0.1:9999;
}

server {
    listen 8080 ssl;
    ssl_certificate     ...;
    ssl_certificate_key ...;

    server_name my.site.com;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://swampdragon;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
With this configuration the settings file is correctly served over HTTPS but the `window.swampdragon_host` variable still delivers an HTTP url.

My question is if this can be fixed by just adding some nginx configuration because the only solution I came up with was to set the X-Forwarded-Proto header to HTTPS and modify the settings_provider.py file in swampdragon to get the protocol from this header.

**Comment by jonashagstedt** [comment]
Have you tried setting `DRAGON_URL='https://...'` (replace the dots with your host)?

**Comment by Mortymus** [comment]
No, I haven't used it yet. But as far as I understand the code the DRAGON_URL is only used for the template tag which loads the settings.js file. As I said, loading the settings file over HTTPS works perfectly fine for me. The problem is the url returned in the `window.swampdragon_host` variable.

**Comment by jonashagstedt** [comment]
Aah right you are.

https://github.com/jonashagstedt/swampdragon/blob/a02794199f8ed38be5310a2205c5c3957189f0b9/swampdragon/settings_provider.py

That's the culprit.

I will sort this one out now

**Comment by jonashagstedt** [comment]
You can try it now with `pip install -e git+https://github.com/jonashagstedt/swampdragon.git@#egg=swampdragon`

(you probably have to `pip uninstall swampdragon` first)

Set the `DRAGON_URL` to use https instead of http.

**Comment by Mortymus** [comment]
Unfortunately I ran into another issue after upgrading to the newest swampdragon version which I need to fix first (#39).

**Comment by jonashagstedt** [comment]
There was another person who struggled with https today as well.

I have tested this using `stunnel` and it works.

I will release a new version soon (coming days I hope) but for now use the the aforementioned `pip install -e git+https://github.com/jonashagstedt/swampdragon.git@#egg=swampdragon`.

Looking at the other issue now

**Comment by cho-is** [comment]
+1

Thanks for the update

**Comment by Mortymus** [comment]
Working for me too. Thanks.

**Comment by jonashagstedt** [comment]
Brilliant! I'll close this issue when I push the new release to pypi.
