### ISSUE TITLE
Angular Service and RequireJS

### ISSUE THREAD

**Issue by Mortymus** [jonashagstedt/swampdragon#39]
Hi,

when updating to the newest version of Swampdragon I have the problem that the Angular service is not working anymore.

I load most of the javascript files using require.js. The problem occours when the Angular service is loaded:
```
ReferenceError: swampdragon is not defined
    at Object.<anonymous> (services.js:23)
```

The problem is that https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/angular/services.js tries to access the global variable `swampdragon` which is not defined.
I think this has something to do with the recently introduced AMD support. When swampdragon.js is loaded via require.js it doesn't expose a global variable and the Angular service runs into this error.

**Comment by jonashagstedt** [comment]
Can you provide me with an example to test (I haven't used require.js before)?

Does accessing `window.swampdragon` work (where `swampdragon` doesn't)?
If that's the case then I could simply change the JS to reference `window.swampdragon` instead

**Comment by Mortymus** [comment]
`window.swampdragon` is also not accessible.

Here is a minimalistic example. It assumes that angular is already loaded and initialized.
``` javascript
require.config({
    paths: {
        "swampdragon": "path/to/swampdragon", //path to swampdragon.js
        "angularService": "path/to/services" //path to swampdragon angular services.js
    }
});

require(['swampdragon'], function(){
    require(['angularService'], function(){
        //Using the $dragon service in here should throw the error
    });
});
```

**Comment by jonashagstedt** [comment]
This is a tricky one.
I am not sure what the ideal approach to this is since I never use require.js

Any suggestions?

**Comment by Mortymus** [comment]
One solution would be to change swampdragon.js such that it exposes the global `swampdragon` variable even when it detects AMD. The same approach is used by jQuery to preserve compatibility with non AMD plugins.

**Comment by jonashagstedt** [comment]
Digging through some blogs on the subject. Since swampdragon is built as stand-alone this is supposed to work:


    require('swampdragon.js', function (swampdragon) {
      // swampdragon should work no
    });

Taken from this blog: http://www.forbeslindesay.co.uk/post/46324645400/standalone-browserify-builds

**Comment by Mortymus** [comment]
This will not work with require.js as the required javascript files are loaded asynchronously and the swampdragon variable is only accessible in the local scope. However one workaround for require.js users would be the following:
```
require(['swampdragon'], function(swampdragon){
   //Set the global swampdragon variable manually
    window.swampdragon = swampdragon;
    require(['angularService'], function(){
        //Now swampdragon is accessible by the $dragon service
    });
});
```

**Comment by jonashagstedt** [comment]
Does that work out of the box or does it need to be part of swampdragon.js (or swampdragon.min.js)?

**Comment by Mortymus** [comment]
This works without any modifications to the current swampdragon code.

**Comment by jonashagstedt** [comment]
There are various ways this can go:

*  If you fancy writing a short blog post about this I'm happy to post it on swampdragon.net
*  Someone who understands require.js makes a pull request (note that the js is built each time so I would have to incorporate it in the build step)
*  A separate repo for require.js (someone made one for bower today)
*  A separate js file for require.js

At this point (being past midnight) I'm not sure so any suggestions would be welcome

**Comment by Mortymus** [comment]
A will have another look into this issue the next days and see if I come up with a better solution. For now I will stick to the workaround. Thanks for your support so far.

**Comment by jonashagstedt** [comment]
No worries. It would be great to get require.js support in since I can imagine a lot of people would want it.
In the meantime I'll refer anyone who has the same problem to this issue.

**Comment by jonashagstedt** [comment]
Closing this for now as this seems to be working. If someone comes up with suggestions or run into issues feel free to reopen the issue

**Comment by abdulwahid24** [comment]
I am also facing the same problem, As I have implemented django as rest api backend and frontend is standalone with AngularJS. I would prefer to install angular service using bower so it would be great if we get an option such as `bower install swampdragon` which will give us swamp dragon angular service. 

Correct me if I am wrong.
