### ISSUE TITLE
Is it possible to call send multiple times from one router call?

### ISSUE THREAD

**Issue by heratech** [jonashagstedt/swampdragon#4]
Hi,
 Is it possible to call send multiple times from one router call?
I want to from the client send a query and as the results come back from the query push them to the client from the server (1 to 1 message).
Also I am struggling to get the chat_example running (CSRF errors) - anything I need to know? Django 1.7

Thanks for a great library.

**Comment by cho-is** [comment]
I am also getting `CSRF verification failed. Request aborted.`with the chat example. 
Just trying submitting some messages on different windows and it is saying ` CSRF token missing or incorrect.`

**Comment by jonashagstedt** [comment]
that means you are submitting a form to a django view
