### ISSUE TITLE
Can you get request.user in ModelRouter?

### ISSUE THREAD

**Issue by cho-is** [jonashagstedt/swampdragon#40]
Is there a way to get `request` in ModelRouter?

**Comment by jonashagstedt** [comment]
The short answer is no.
What do you need it for?

**Comment by cho-is** [comment]
I need to save the request user id

**Comment by jonashagstedt** [comment]
Ah sorry, I totally missed the "user" in the title of the question!

If you use: https://github.com/jonashagstedt/swampdragon-auth
you can access the user in your router via `self.connection.user`

**Comment by cho-is** [comment]
I am using django-allauth for that purpose. Basically the only thing I need to save is the logged in user id.

**Comment by jonashagstedt** [comment]
`swampdragon-auth` isn't an alternative authentication process, it's a way to access the signed in user

**Comment by cho-is** [comment]
awesome! I will give a try!
