### ISSUE TITLE
Serializers Relationships

### ISSUE THREAD

**Issue by cho-is** [jonashagstedt/swampdragon#42]
I read in the docs that something like this would bring the relation:

```

class UserSerializer(ModelSerializer):
    class Meta:
        model = 'app.User'


class ChatSerializer(ModelSerializer):
    username = 'chat.UserSerializer'

    class Meta:
        model = 'chat.Chat'
        publish_fields = ('message', 'user', 'username', 'date', )
```
But username is null. Any clue?

**Comment by jonashagstedt** [comment]
Remove user serializer if you only need the username, and change ChatSerializer to this:


    class ChatSerializer(ModelSerializer):
        class Meta:
            model = 'chat.Chat'
            publish_fields = ('message', 'username', 'date', )

        def serialize_username(obj, *args, **kwargs):
            return {'username': obj.user.username}

**Comment by cho-is** [comment]
I was getting `AttributeError: 'ChatSerializer' object has no attribute 'user'`

model is 
```
class Chat(SelfPublishModel, models.Model):
    user = models.ForeignKey(User, null=True)
    date = models.DateTimeField(default=timezone.now)
    message = models.TextField()

    serializer_class = ChatSerializer

    class Meta:
        ordering = ("date",)
```

**Comment by jonashagstedt** [comment]
Ah sorry, my bad.
It should probably be something like `obj.instance.user.username`

**Comment by cho-is** [comment]
working! many thanks!

**Comment by VVILD** [comment]
@jonashagstedt 

What id we dont require just the username and the full user class?
