### ISSUE TITLE
javascript error on hearbeat

### ISSUE THREAD

**Issue by jerzyk** [jonashagstedt/swampdragon#43]
Uncaught ReferenceError: channel is not defined swampdragon.js:157

line responsible for this error:
'''
eventHandler.emit('heartbeat', [channel, e.data]);
'''
and there are no 'channel' variable, even more there are no 'channel' property in event's data

**Comment by jonashagstedt** [comment]
I really need more to go on than that.

**Comment by jerzyk** [comment]
file swampdragon/static/swampdragon/js/src/connection.js function function onmessage liine 103
there is a reference to "channel" variable which is not define here and is not in global scope.

"e" variable (function parameter) may have "event" property, but statement before checks for it and in such case there are no "chanel" info at this moment. I suppose this shoud be removed or replaces by null, to keep number of parameters constant

**Comment by jonashagstedt** [comment]
What version of SD are you using?

Could you paste your JS so I can see how you are implementing it as well.

**Comment by jerzyk** [comment]
why? This error is not dependent on implementation but in swampdragon javascript code

**Comment by jonashagstedt** [comment]
Right but you are so far the only one who has reported this and I need a way to replicate this

**Comment by jonashagstedt** [comment]
I'm closing this as I don't have enough information to work with.

**Comment by bufke** [comment]
I actually have this too. My project is on [git](https://github.com/bufke/chat-experiment). Happy to debug.

Using Linux via docker. If you happen to have docker install it should be easy to reproduce.

**Comment by bufke** [comment]
The connection's on_heartbeat still fires on the server. This issue actually doesn't affect me negatively at all but does seem like a valid issue. Perhaps this emit handler call is related to the legacy $dragon.onHeartbeat which no longer seems present? Just guessing.

**Comment by jonashagstedt** [comment]
@bufke thank you for sharing your code. 
It took me but a minute to actually solve this issue once I could see it, very helpful!

It's fixed in the 0.4.3 branch

**Comment by bastianh** [comment]
I ran into the same problem .. what is the state of the 0.4.3 branch? is it usable? Or what can I do to prevent the bug in 0.4.2?

**Comment by ghost** [comment]
I'm also getting the same error in my application 
SwampDragon==0.4.2.2
It's working fine as a single app but getting error when I include it in my other project

**Comment by jerzyk** [comment]
I've dropped swampdragon long time ago, there are much better alternatives, plus you do not get shit while reporting errors. to name top one, that almost get into the django: [django channels](https://github.com/django/channels)

**Comment by ghost** [comment]
yeah. you are right. but, I have already used it. could you please help me ?
