### ISSUE TITLE
How to create model with existing related field?

### ISSUE THREAD

**Issue by CptLemming** [jonashagstedt/swampdragon#44]
I'm trying to create a `Message` model using Javascript, and I've been left scratching my head.

When I use `create` on my router and pass in a related user object, I receive an error `"Duplicate entry 'test' for key 'username'"`; The serializer is trying to create a new user model rather than hook into the old one.

Have I missed something obvious, or is there no way to create a model re-using an existing foreign key?

## Create code
````javascript
var data = {
  user: { id: 1, username: 'test', password: 'test' },
  body: 'testing'
};
swampdragon.create('message', data, function (context, data) {
  console.log('MessageStore: onCreate success.', context, data);
}, function (context, data) {
  console.log('MessageStore: onCreate failed.', context, data);
});
````

## Model
````python
class Message(SelfPublishModel, models.Model):
    serializer_class = MessageSerializer

    user = models.ForeignKey(User, related_name='messages')
    body = models.TextField(blank=True)
```

## Serializers
````python
class UserSerializer(ModelSerializer):

    class Meta:
        model = User
        publish_fields = ('id', 'username')
        update_fields = ('username', 'password',) # Had to add these to prevent validation fail on the model, but don't really want these to be updateable

class MessageSerializer(ModelSerializer):
    user = UserSerializer

    class Meta:
        model = 'chat.Message'
        publish_fields = ('body', 'user', )
        update_fields = ('body', 'user', )
```

**Comment by jonashagstedt** [comment]
If's probably best never to create a user model like this.
Anyone could just change the JS to post whatever they wanted, so someone could effectively overwrite all your users.

To fix your actual problem I believe you need to add `id` in `update_fields`.
The model serializer will ignore anything that isn't in `update_fields` or passed as initial data.

Again, I would strongly recommend not creating the user model like this.
Instead let the user data be read only (publish user data but don't include it in the update_fields), and
implement `get_initial`.

    def get_initial(verb, **kwargs):
        # verb would be either 'create' or 'update'
        # but since we need the user for both we don't bother checking
        user = User.objects.get(kwargs['user_id'])
        return {'user': user}
        
This way you can pass `user_id` to the router and not have to worry about anyone changing any users.

If the user object is the author of the message then I would use swampdragon-auth, and use the `user` object from `self.connection.user` in the router.

**Comment by CptLemming** [comment]
Ahh so there is no built in mechanic to load the related fields? I need to add something to the router to do this myself? I guess that makes sense.

Just to clarify, I didn't want to create a user in this way (as you say, that probably wouldn't work out well for me :)).

I guess from using Django models, and DRF in particular, where you can supply a foreign key to a model you are creating (rather than instantiating an instance of that relation) and having these work auto-magically for you I had assumed this would be the case here.

Thanks for the help.
