### ISSUE TITLE
Disable writes

### ISSUE THREAD

**Issue by Gromph** [jonashagstedt/swampdragon#45]
I'm experimenting with using swamp dragon with django rest framework(drf). I want all writes to go through our drf api. The main reason is to pass validation and permissions already setup with drf.  Now I want to use swampdragon to notify clients when models have been updated. I got that working using the SelfPublishModel mixin, and the ModelRouter.   But it looks like by default that also allows the model to be created, updated and deleted. What is the best way to disable all writes?  For now I'm thinking of subclassing ModelRouter and override create, update, and delete functions to do nothing.  This is a bit scary though, it would be nice to have an official way to say this route is read only and be certain there is no way the model can be changed via websocket/swampdragon.

Thanks!

**Comment by jonashagstedt** [comment]
Simply set `valid_verbs = ['get_list, 'get_single'']` and if anyone tries it on it will just raise an invalid verb exception.

**Comment by Gromph** [comment]
awesome. thanks.
