### ISSUE TITLE
Document that redis_db has no effect whatsoever, since pubsub does not rely on databases

### ISSUE THREAD

**Issue by NotSqrt** [jonashagstedt/swampdragon#46]
I've been bitten by this:

I thought that using different values in ``SWAMP_DRAGON_REDIS_DB`` would isolate my ``dev`` django context from my ``test`` context, but it is not the case.

cf http://redis.io/topics/pubsub, section ``Database & Scoping``

It happened for me between test and local environments, which is not a big problem, but it can happen between multiple websites if they use the same redis instance.

******

Side note:

I am in an unexpected case where I am using the redis publisher in tests, instead of the mock publisher : at https://github.com/jonashagstedt/swampdragon/blob/9adb5579c507b76e34b6be2e617c42e7b6bcaa19/swampdragon/pubsub_providers/publisher_factory.py#L10, the code looks for ``test`` in ``sys.argv`` but I use ``python manage.py jenkins`` to run tests.

Additionally, this is a rather strange way to switch backends, it would seem more natural and explicit to use something similar to what is done for emails : https://docs.djangoproject.com/en/1.7/topics/email/#dummy-backend

**Comment by jonashagstedt** [comment]
Docs are updated.

Re sys.argv: that's a valid point. 
The 'test' in `sys.argv` is a hack. I'm going to open a separate issue for this.

**Comment by jonashagstedt** [comment]
I've created a new issue for the tests.

**Comment by NotSqrt** [comment]
Thanks for the super fast reaction !

I think it would be nice to provide some sort of isolation, even if ``redis_db`` does not provide it.

A-la-celery, when they need to provide isolation between task priorities, they use ``"channel_name" + "<strange unicode character that has no chance to be used in a regular string>" + priority``.

It should be possible to achieve the same sort of thing in swampdragon:
when publishing or subscribing to a channel, actually pub/sub to channel + isolation_keyword where isolation_keyword can be defined in the settings.

**Comment by jonashagstedt** [comment]
That's a possibility.

There shouldn't be too many places channels are generated in.
A channel prefix would solve this. 

I'll add an issue for that too.
