### ISSUE TITLE
Custom serializer fields are always returned

### ISSUE THREAD

**Issue by CptLemming** [jonashagstedt/swampdragon#49]
If I define a custom field serializer, the field is always included in the output from `serialize` regardless of `publish_fields`:

```python
class UserSerializer(ModelSerializer):
    def serialize_avatar(self, obj):
        return obj.get_avatar()

    class Meta:
        model = User
        publish_fields = ('username', )

serializer = UserSerializer(instance=testUser)
serializer.serialize()
# {"username": "test", "avatar": "/images/test.png"}
```

**Comment by CptLemming** [comment]
While digging through the source code, I noted this test:

```python
def test_serialize_custom_field_not_in_publish_fields(self):
    text_model = TextModel.objects.create(text='hello world')
    result = CustomTextModelSerializer(instance=text_model).serialize()
    self.assertEqual(result['foo'], 'bar')
```

This suggests it is intentional to include custom fields when they are not explicitly included in `publish_fields`.

Should there not be a way to exclude these fields, rather than forcing creation of a 2nd serializer?

**Comment by jonashagstedt** [comment]
Could you give an example of when you would declare a custom serializer field but not include it in the output (what would be the point / purpose of declaring the function if it's never used?)

**Comment by CptLemming** [comment]
In my case I use the serializer in the connection to serialize a list of users:

```python
class UserConnection(HttpDataConnection):
    ...
    def format_users(self):
        users = []
        for participant in self.participants:
            user = participant.get_user()
            user_data = UserSerializer(instance=user).serialize(fields=['username', 'avatar'])
            users.append(user_data)
        return users
    ...
```

I realise this isn't the intended use case, but the current limitation forces me to create multiple serializers rather than being able to re-use a common one.

**Comment by jonashagstedt** [comment]
I'm not quite sure I follow.
You have declared a specific function on the serializer but you don't want to include the output of said function? 
What would be the reason for the custom serializer function in that case?
A base user serializer would be the best place to start in that case and simply inherit from it.

I am working on getting DRF serializers working for 0.4.3

**Comment by jonashagstedt** [comment]
Closing this for now but feel free to add more info and / or reopen if it's still relevant
