### ISSUE TITLE
Possible problem with mapData

### ISSUE THREAD

**Issue by aericson** [jonashagstedt/swampdragon#51]
Shouldn't mapData change the value of datesource and return the new value?

mapData calls mapCreated/mapUpdate/mapDelete and they can possibly assign another object to the datesource reference and return the value such as in [[1]](https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/dist/datamapper.js#L67) [[2]](https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/dist/datamapper.js#L96).

Couldn't that become a problem?

**Comment by jonashagstedt** [comment]
It was a while ago since I wrote the data mapper and it sure could do with an update.
However the bits you are pointing at is if there is no object map.
If you have nothing to map an object by you just have to return it.

**Comment by aericson** [comment]
So, correct usage for it would be to check before if we have something to map?

**Comment by jonashagstedt** [comment]
If you are using the swampdragon serializer the map will be provided when you subscribe

**Comment by aericson** [comment]
Guess it makes sense now, thanks for the help :)
