### ISSUE TITLE
Is it possible for SelfPublishModel to delay publishing until after transaction is committed?

### ISSUE THREAD

**Issue by Gromph** [jonashagstedt/swampdragon#53]
The problem is clients can receive the updated action message for a model before it is actually committed to the database. It goes something like this:

client A does a put to our django rest api to update a model
client B receives notification of the change, and retrieves the model with a regular http get. But it receives the model without any changes that client A just wrote. If we put a second or two delay in the client it does receive the correct changes. 

We're re-requesting the data from rest instead of just using the data from the swamp dragon message because we already have complex serializers set up with django rest framework and don't want to recreate them with swamp dragon serializers just yet. So for now we're just using swamp dragon to trigger the client to refresh from http rest.

We're using Mysql innodb tables with transaction support turned on with "ATOMIC_REQUESTS": True  set in settings.DATABASES

Another reason for delaying until after the transaction commits is to avoid sending out incorrect data if the transaction fails.

**Comment by jonashagstedt** [comment]
I would say don't use the self publishing model.
Just publish the model manually when it's ready. If you don't use the data mapper you could even go as far as publish the data from the rest framework serializer

**Comment by jonashagstedt** [comment]
The short answer is no (as of writing this at least) so I'm closing this issue.

You can not delay publishing when updating a model.
You can when creating a model but that doesn't help with this issue of course
