### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by bubuntux** [jonashagstedt/swampdragon#54]
`>>manage makemigrations `

File "/virtualenvs/project/lib/python3.4/site-packages/swampdragon/serializers/serializer_tools.py", line 5, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named 'django.db.models.related'

`>>python --version`
Python 3.4.2

`>>pip freeze`
certifi==14.05.14
django-debug-toolbar==1.3.0
django-redis-sessions==0.4.0
Django==1.8
pip-tools==0.3.5
pycrypto==2.6.1
python-dateutil==2.4.1
redis==2.10.3
six==1.9.0
sockjs-tornado==1.0.1
sqlparse==0.1.14
SwampDragon==0.4.1.2
tornado-redis==2.4.18
tornado==4.1

**Comment by hamotoJohn** [comment]
That looks like it's related to: https://code.djangoproject.com/ticket/21414

**Comment by bubuntux** [comment]
Also getting this warning 
python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  return f(*args, **kwds)

swampdragon/model_tools.py : line 1 
from django.db.models.loading import get_model as get_django_model

**Comment by jonashagstedt** [comment]
This is fixed in the 0.4.2 branch.
Since 1.8 just came out I won't focus on the 1.9 warning just yet.
