### ISSUE TITLE
How to get the amount of new messages according to different users.any example?

### ISSUE THREAD

**Issue by kingctan** [jonashagstedt/swampdragon#56]
I am new to SD.How to get the amount of new messages according to different users.any example?

**Comment by jonashagstedt** [comment]
Not sure I follow. In what context?

**Comment by kingctan** [comment]
for example,the twitter's message notification,it will show you how many new twitters added.

**Comment by jonashagstedt** [comment]
If you are doing notifications just have an `is_read` flag on your notification model.
When a user receives a new notification you can call a router with the notification id to set `is_read` to True (or something similar).

SD is not specifically for notifications, you have to write that part your self.
