### ISSUE TITLE
Swampdragon Javascript Client Code

### ISSUE THREAD

**Issue by jmurphyau** [jonashagstedt/swampdragon#57]
Hi

I'm interested in developing an Ember addon for swamp dragon but I'm struggling on where to start with the client code. I'm looking at the repo 'swampdragon-bower' and also this repo in the folder 'swampdragon/swampdragon/static/swampdragon/js'.. 

What code should I start with to develop something that relies on the swampdragon frontend code?

Additionally - I think [calling connect()](https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/src/connection.js#L110) and [accessing window variables](https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/src/connection.js#L15) in the [connection.js](https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/static/swampdragon/js/src/connection.js) file is going to cause problems for me and I'm wondering what your openness is to changing that? 
It doesn't seem like there is any way to 'initialize' swampdragon on the client side - it appears to all rely on global variables and functions which get executed as soon as the script is run on the client - it doesn't look like there is any way to stop this?

**Comment by jonashagstedt** [comment]
I would recommend working from https://github.com/jonashagstedt/swampdragon/tree/master/swampdragon/static/swampdragon/js/src
If you are using commonjs.

I am happy to accept PR's as long as they are tested and if you have any suggestions on changes I am open to listen, the main concern is to try to keep it all backwards compatible.

You do need the global variable for people who simply want to include SD without building the JS in any way or form.

**Comment by jmurphyau** [comment]
Ok awesome. I'll start looking into this.

Separately - what is your opinion on separating the client code into its own repository?

**Comment by jonashagstedt** [comment]
I have thought about it, but there are a lot of people who just want to install and go, with as little setup as possible.
For these people it's important to be able to copy and paste some code from the docs and it will just work.

**Comment by jonashagstedt** [comment]
Closing this issue for now. Feel free to reopen it or just comment on it
