### ISSUE TITLE
Using just push notifications

### ISSUE THREAD

**Issue by owais** [jonashagstedt/swampdragon#6]
This looks very interesting. Most django projects have serializers setup in some form or other. Is it possible to use other serializers like django-rest-framework with this?

..or is it possible to just send push events to the browser without integrating the models and other things?

**Comment by vivek1may** [comment]
This is great work. Just to add in the chat_example, mentioned JS controller(chat-controller.js) is not included but app.js. 

And i tried with 
publish_data(channel='local-channel',kwargs)

it is not working. 

And with publish function it is working for all channel names. Can you please explain how to limit messages to specific channels in a same router...
