### ISSUE TITLE
SD 0.4.2 + Django 1.8 + AngularJS 1.3.15 - No route named " Exception

### ISSUE THREAD

**Issue by ZuSe** [jonashagstedt/swampdragon#60]
Hello folks,

I was looking for some smart way to provide notifications and meeting invites towards my users. I finally found SD. I really like it, you did a great job. I tried out the quick start tutorial, which works for me. 
So it was time to include SD into my project. That does not work all.

Whenever I use callRouter() or try to subscribe to a router (i.e. notifications) Tornado throws:

ERROR:tornado.application:Uncaught exception in /data/485/58blrxo3/websocket
Traceback (most recent call last):
  File "<project_root>venv\lib\site-packages\sockjs\tornado\transports\websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "<project_root>venv\lib\site-packages\sockjs\tornado\session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "<project_root>venv\lib\site-packages\swampdragon\connections\sockjs_connection.py", line 90, in on_message
    raise e
  File "<project_root>venv\lib\site-packages\swampdragon\connections\sockjs_connection.py", line 86, in on_message
    handler = route_handler.get_route_handler(data['route'])
  File "<project_root>venv\lib\site-packages\swampdragon\route_handler.py", line 334, in get_route_handler
    raise RouteException('No route named "{}"'.format(name))
swampdragon.route_handler.RouteException: No route named "connection-test"

My routers look like this:

class NotificationRouter(ModelPubRouter):
    valid_verbs = ['subscribe']
    route_name = 'notifications'
    model = Notification
    serializer_class = NotificationSerializer

    @login_required
    def subscribe(self, **kwargs):
        super().subscribe(**kwargs)

    def get_subscription_contexts(self, **kwargs):
        return {'user_id': self.connection.user.pk}

route_handler.register(NotificationRouter)

class ConnectionTestRouter(BaseRouter):
    route_name = 'connection-test'
    valid_verbs = ['test']

    def test(self,**kwargs):
        self.send({"Status":"OK"})

route_handler.register(ConnectionTestRouter)

I really have no idea what is going wrong. Is there a way to check which routes are registered?

Best,
ZuSe

**Comment by abdulwahid24** [comment]
@ZuSe I am also facing the similar problem, Did you get any solution ?
