### ISSUE TITLE
Issues starting server.py

### ISSUE THREAD

**Issue by andrewfam** [jonashagstedt/swampdragon#61]
The tutorial doesn't seem to be working out of the box.

Starting server.py with the following code and heading to the url, I get a 404 on tornado web.py. The file is there. Any reason for this? My manage.py works fine.

--- server.py
#!/usr/bin/env python
import os
import sys

from swampdragon.swampdragon_server import run_server

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tutorial.settings")

host_port = sys.argv[1] if len(sys.argv) > 1 else None

run_server(host_port=host_port)

--traceback
Traceback (most recent call last):
  File "/Users/andrewfam/.virtualenvs/swampdragon/lib/python2.7/site-packages/tornado/web.py", line 1323, in _execute
    result = self.prepare()
  File "/Users/andrewfam/.virtualenvs/swampdragon/lib/python2.7/site-packages/tornado/web.py", line 2014, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

**Comment by andrewfam** [comment]
Nevermind it seems to be working now but hitting the url on server.py still shows the error

**Comment by jonashagstedt** [comment]
That's just the url that SwampDragon is running on. You don't browse directly to it, but your client will use it as an endpoint.

If you are using it for a website (probably the most conventional usage) the JS client would connect to that endpoint
