### ISSUE TITLE
Unicode errors

### ISSUE THREAD

**Issue by jmarks1992** [jonashagstedt/swampdragon#62]
Hey --

Running into problems with the serializer with special characters. Getting lots of errors like the below:

ERROR:tornado.general:WebSocket
Traceback (most recent call last):
  File "/webapps/quorum-site/local/lib/python2.7/site-packages/sockjs/tornado/transports/websocket.py", line 60, in o$
    self.session.on_messages(msg)
  File "/webapps/quorum-site/local/lib/python2.7/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/webapps/quorum-site/local/lib/python2.7/site-packages/swampdragon/connections/sockjs_connection.py", line 79$
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 26: ordinal not in range(128)

This appears to happen even when a field is being serialized without special methods -- is this a problem on my end (if so, would love help fixing it) or with Swampdragon? Running Django 1.7, Postgres database.

**Comment by jonashagstedt** [comment]
This is an odd one. u2019 is a single quote as well so that should definitely not be an issue
Can you provide some information for me to replicate this?

**Comment by jmarks1992** [comment]
I'll try to create a minimal example to replicate. In the meantime, is there any chance I've missed something obvious elsewhere?

**Comment by jonashagstedt** [comment]
Without seeing any code it's a mystery to me

**Comment by jmarks1992** [comment]
Hi Jonas -- 

Thanks for your help. We were able to figure it out -- I ended up removing the special characters from the strings altogether and reencoding them on the front-end. Not the most beautiful solution but works for now!

Thanks,
Jonathan

**Comment by jonashagstedt** [comment]
I'll close this for now. I do wish I knew what caused it but we'll see if someone else has the same issue they can reopen this one.
