### ISSUE TITLE
Issue with Django app and wstunnel proxy to SwampDragon on same host and port

### ISSUE THREAD

**Issue by mback2k** [jonashagstedt/swampdragon#65]
I tried to deploy SwampDragon on webgcal.uxnr.de using mod_proxy_wstunnel for apache2. Please see the following conversation at the httpd mailinglist for more information: http://markmail.org/thread/lcpscrlxn3yai6xq

My problem is that the browsers Firefox, Safari and Chrome are re-using the upgraded websocket connection for non-websocket traffic. This means that navigating to another page once SwampDragon was used, results in a 404 error returned by the Tornado websocket-server.

Maybe you can help me with this from the client perspective.

**Comment by mback2k** [comment]
I just figured out the configuration issue causing my problem.

Original configuration mod_proxy_wstunnel with SwampDragon:

    ProxyPass /data/ ws://127.0.0.1:9001/data/
    ProxyPassReverse /data/ ws://127.0.0.1:9001/data/
    ProxyPass /settings.js http://127.0.0.1:9001/settings.js
    ProxyPassReverse /settings.js http://127.0.0.1:9001/settings.js
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyVia On

The following configuration for mod_proxy_wstunnel with SwampDragon works fine:

    ProxyPassMatch /data/(\d+)/(\w+)/websocket ws://127.0.0.1:9001/data/$1/$2/websocket
    ProxyPass /data/info http://127.0.0.1:9001/data/info
    ProxyPassReverse /data/info http://127.0.0.1:9001/data/info
    ProxyPass /settings.js http://127.0.0.1:9001/settings.js
    ProxyPassReverse /settings.js http://127.0.0.1:9001/settings.js
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyVia On

The issue was caused by the fact that /data/info is requested before a WebSocket-upgrade request to /data/(\d+)/(\w+)/websocket is performed. Because /data/info was redirected to the WebSocket-server using the same rule as /data/(\d+)/(\w+)/websocket before, mod_proxy_wstunnel continued to also forward all HTTP-traffic to the WebSocket-server.

Hope this helps in case anyone else runs into the same problem. You have to make sure that ws:// or was:// forwarding is only configured for the actual WebSocket-URL and does not affect any other requests.

See: http://markmail.org/message/sve66pqoej6ajm6r

**Comment by jonashagstedt** [comment]
Excellent, and thanks for posting the solution here for others

**Comment by mback2k** [comment]
No problem. You are welcome.

The following configuration also takes the other SochJS transports, like xhr and xhr_streaming into account:

    ProxyPassMatch /data/(\d+)/(\w+)/websocket ws://127.0.0.1:9001/data/$1/$2/websocket
    ProxyPass /data/ http://127.0.0.1:9001/data/
    ProxyPassReverse /data/ http://127.0.0.1:9001/data/
    ProxyPass /settings.js http://127.0.0.1:9001/settings.js
    ProxyPassReverse /settings.js http://127.0.0.1:9001/settings.js
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyVia On
