### ISSUE TITLE
Channels are not properly isolated from each other

### ISSUE THREAD

**Issue by mback2k** [jonashagstedt/swampdragon#67]
It seems like action messages on channels are not properly isolated from each other.
If I have 25 channels to 1 router for 25 invidual objects by id, setup like this:
```
["{\"route\":\"website\",\"verb\":\"subscribe\",\"args\":{\"id\":7075348,\"channel\":\"website-7075348\"},\"callbackname\":\"cb_0\"}"]
["{\"route\":\"website\",\"verb\":\"get_single\",\"args\":{\"id\":7075348},\"callbackname\":\"cb_1\"}"]
a[{"channel_data":{"local_channel":"website-7075348","action":"subscribe","remote_channels":["website|id:7075348"]},"data":[],"context":{"client_callback_name":"cb_0","state":"success","verb":"subscribe"}}]
a[{"data":{"status":"Finished syncing website","_type":"website","name":"24","enabled":true,"updated":"2015-04-21 20:01:24+00:00","id":7075348},"context":{"client_callback_name":"cb_1","state":"success","verb":"get_single"}}]
```
An update to one single object, causes the following 24 additional deletion messages, even though the object was not deleted:
```
a["{\"action\": \"updated\", \"data\": {\"status\": \"Parsing website\", \"_type\": \"website\", \"id\": 7075348}, \"channel\": \"website|id:7075348\"}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
a["{\"action\": \"deleted\", \"data\": {\"id\": 7075348}}"]
```
And this seems to cause that further updates to the other objects are no longer applied.

**Comment by jonashagstedt** [comment]
This is related to another issue that has been logged.

The logic behind it (which is currently flawed) is that when a model no longer match a channel it should be removed.

I'll try to get this issue sorted in the 0.4.2 release.

**Comment by mback2k** [comment]
The channel is now included in the delete messages (action=deleted), but for some reasons there is sill a delete message being send if the object is actually not deleted and still matches the query. I filter channels on the object's id.

**Comment by jonashagstedt** [comment]
Yes I figured this wasn't resolved but I didn't want to hold up 0.4.2 any longer.
I've started the work on 0.4.3 already

**Comment by jonashagstedt** [comment]
I'm digging in to this issue and more information would be very helpful.

A delete message is sent if you remove a FK connection between a subscribed object.
In case you are displaying a list of objects and a related object is no longer referenced then it should be removed from the list.

More information would help greatly, and a unit test demonstrating the issue would of course be the best one.

Some router info would help too, especially generating the subscription context.

**Comment by mback2k** [comment]
[Here](https://github.com/mback2k/django-webgcal/blob/master/webgcal/apps/webgcal/routers.py) you can find my routers. And [here](https://github.com/mback2k/django-webgcal/tree/master/webgcal/apps/webgcal/subtasks) you find the Celery tasks updating the individual objects. I am displaying those individual objects, e.g. there is an AngularJS controller instance for each individual object. And none of these objects are actually deleted.

**Comment by jonashagstedt** [comment]
This has been a hard one to trace down, and I am not sure I've managed to replicate this.

Could I ask you to try this with the 0.4.3 branch and see if the problem still remains.
I've rewritten a lot of code that handles the publication of `DELETE` messages.

**Comment by mback2k** [comment]
@jonashagstedt Thank you very much, Jonas. It seems like your rewrite of the ```DELETE```message handling solved the problem for my website. I only see ```UPDATED```messages now. :-)
Sorry, that I could not provide you with a sample.

**Comment by jonashagstedt** [comment]
Brilliant!

I'll close this for now, hopefully I'll be able to push this to pypi soon (have a few more outstanding issues)

**Comment by mback2k** [comment]
Any ETA on a new release to PyPI?
