### ISSUE TITLE
connection.js reconnect issue

### ISSUE THREAD

**Issue by basilkohler** [jonashagstedt/swampdragon#68]
When the sd server response but does not establish a connection (e.g. unauthorized user with swampdragon-auth) connection.js is currently broken resulting in infinite reconnect tries. 
The fix is simple:
* rename connectionAttempt -> connectionAttempts
* remove line 35 because, it resets the counter on each try

But in that situation the clients probably wants to connect explicitly anyway (check if user is authed -> connect swampdragon). Simplest solution would be to just expose the connection.connect function and still always do the connect on start. Otherwise something configuration based (I guess you would want that the connection is always established by default).

I could look into it if you are not having any changes or other plans for this.

**Comment by jonashagstedt** [comment]
Sure, have a look at it.
The connection attempts counter is a bit simple but a solution needed to be in place to reconnect in case of a connection drop.
This connection needs to be reset if a successful connection is established.

On that note though, a connection never requires authentication.
You should still be able to connect unless you specifically override the connection if no user object exists, so I'm not sure how you get a disconnect the user is not authenticated.

**Comment by basilkohler** [comment]
Oops, you are right! Connection is always established. I have a custom connection which sets a flag if a user is online depending on the socket connection, but i forgot to check if user is None and I did not see any error output. The above fix is still necessary if you want the reconnect mechanism to work as intended.

I would argue that it could make more sense to keep polling with the longest interval time instead of just stopping to reconnect?

Anyway, my problem is resolved for now, thx!

**Comment by jonashagstedt** [comment]
No prob.
Are you doing something to keep track of online users?

**Comment by basilkohler** [comment]
Yes, I use a custom swampdragon-auth HttpDataConnection overriding the on_open/on_close/heartbeat messages to check/set the online status.

**Comment by jonashagstedt** [comment]
The heartbeat is good to use for this to clean up anything that is "missed" by the closing connection (since loads of things can go wrong along the way, like the Redis server going down, etc. etc.).

I've done all this in https://github.com/jonashagstedt/swampdragon-notifications
would love to see how you solved some of the problems etc.

**Comment by basilkohler** [comment]
Did some digging to find out why I did not see the error. First of all, when I just run swampdragon I did not see any output. In issue #37 I found the logging config which let mee see some stuff. However, they used 'level': 'ERROR', but tornado prints these calls in DEBUG mode. Not sure if I did something wrong that I don't see errors or other output, but it works with the following:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console':{
            'level':'DEBUG',
            'class':'logging.StreamHandler',
            'formatter': 'simple'
            },
        },
    'loggers': {
        'django.request': {
            'handlers':['console'],
            'propagate': True,
            'level':'DEBUG',
            },
        'tornado.general': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
```

**Comment by jonashagstedt** [comment]
I've had a few reports on errors not being visible.
I have never had this happen on any project I've done with SD so I am a bit confused why this is happening for some

**Comment by basilkohler** [comment]
I had a quick look at swampdragon notifications. Looks very convenient for notifications!

For the online status I have a simple model with the status and last modified which is updated, triggering my custom self publish implementation on all subscribers, so nothing special.

Im not using the default swampdragon serializer/publishers because I have existing DRF serializers and I needed instance based filtering in some cases.

Here a short explanation:
I created a custom base router with two methods. One method is called when a user subscribes on a router and should return a list of channels. This way a router can decide what channels a specific users is allowed to subscribe to, for example a user is only allowed to subscribe on userprofiles of his "friends", resulting in channels: `['userprofile|id=1', 'userprofile|id=5']`. 
The counterpart is called at the time a model is published. It should return a list of channels this specific instance should be published to (e.g. `['userprofile|id=5']`). 

To implement notifications, the subscribe-method would return `['notification|user_id=user.id']` or nothing depending if there is a authed user on the connection. The publish-method would return `['notification|user_id=notification.user.id']` and only the specific user would receive it.
The model in this case should probably be in "PublishCreate" mode (delete/update of a notification probably is not interesting for the client).

When publishing I take a rest framework serializer to create the data. Ofcourse this loses the per field update, but for my purposes so far I don't think that is too important. It might break the datamapper as well, not sure. 

Now this is only half of the story, have not looked into client -> server part at all. I just use the DRF api for that. 

It is in a very early/rough state, but I could create a gist or maybe even a repo to show the code (it is not much yet).
