### ISSUE TITLE
AngularJS get_object

### ISSUE THREAD

**Issue by andrewuscf** [jonashagstedt/swampdragon#72]
I am new to Swampdragon and angularjs. I have came across a problem. How would I set up a get_object from a router like this in angular?

    class InterestRouter(ModelRouter):
        route_name = 'interestrouter'
        serializer_class = ActiveInterestSerializer
        model = Interest

        def get_object(self, **kwargs):
            return self.model.objects.filter(user=kwargs['user']).filter(user=kwargs['user2'])

        def get_query_set(self, **kwargs):
             return self.model.objects.all()

So the model has a many to many field to users. I only want to receive the objects that both users are in.
Here is a getList but I want to use get_object instead.

     $dragon.getList('interestrouter', {user:parseInt(eachuser), user2:parseInt(user)}).then(function(response) {
                        
                    });

**Comment by jonashagstedt** [comment]
Just change getList to `getSingle`
