### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by wleev** [jonashagstedt/swampdragon#73]
I had swampdragon running a month ago, but ever since I resume development and udpated swampdragon I keep getting CORS errors.

    The connection to ws://186.73.45.170:6971/data/513/w70dmxye/websocket was interrupted while the page was loading. swampdragon.min.js:5:0
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://186.73.45.170:6971/data/info. This can be fixed by moving the resource to the same domain or enabling CORS.

How I start the connection:
index.html

    <script src="http://186.73.45.170:6971/settings.js" type="text/javascript"></script>

app.js

    swampdragon.open(function() {
        swampdragon.subscribe('shakemap-route', 'shakemap');
        swampdragon.subscribe('station-route', 'station');
    });

    swampdragon.onChannelMessage(function(channels, messages) {
        console.log('onchannelchannels:', channels);
        console.log('onchannelmessages:', messages);
        Shakescreen.commands.execute('setShakemap', messages['data']);
    });

manage.py

    ./manage.py runsd 0.0.0.0:9999

Don't worry about the port, it's being forwarded to my public ip's 6971.

Any advice?

**Comment by wleev** [comment]
And on my local box I'm not getting any update/create event through anymore. I've tried clearing my local db, the Redis instance and tried changing route names, but I can't get a single channel message through. I'm using SelfPublishModel with a ModelRouter like in the tutorial.

    class Shakemap(SelfPublishModel, models.Model):
        serializer_class = ShakemapSerializer    
        time         = models.DateTimeField()
        mag          = models.FloatField()
        lon          = models.FloatField()
        lat          = models.FloatField()
        region       = models.CharField(max_length=400)
        event_id     = models.CharField('SeisComP Event ID', max_length=100, 
                                                            null=True, blank=True, unique=True)

        def __unicode__(self):
            return self.event_id 

    class ShakemapRouter(ModelRouter):
        route_name = 'shakemap-route'
        serializer_class = ShakemapSerializer
        model = Shakemap
    
        def get_object(self, **kwargs):
            return self.model.objects.get(pk=kwargs['event_id'])

        def get_query_set(self, **kwargs):
            return self.model.objects.all()

Is there any way to debug swampdragon to see where the issue is?

**Comment by jonashagstedt** [comment]
Which version did you upgrade from?
If it was a big update it might be worth checking the change log.

Have your IP changed perhaps (remember to set `DRAGON_URL`)?

You can debug using (i)pdb just like any other python app.

**Comment by wleev** [comment]
Sorry for the delay, have been quite busy.

Cors has nothing to do with it (at least not on my local box). I've pinpointed the problem down to 'model_publisher.py' where 'all_model_channels' is not being populated ( by the redis_publisher). Any idea as to how I could proceed on solving this issue?

Thanks.

**Comment by jonashagstedt** [comment]
Which version of Django and SD are you using?
If you run things locally (without defining the port etc.) what happens?

**Comment by wleev** [comment]
I am running Django 1.7.8 and SD 0.4.2.2. Locally I have limited functionality with SwampDragon. I can do manual stuff like getList, but my model saves are not being published. I tracked it down to the redis_publisher not having any channels available, like I mentioned in my previous post.

**Comment by jonashagstedt** [comment]
Could you show me the code for the serializer as well?

**Comment by wleev** [comment]
from swampdragon.serializers.model_serializer import ModelSerializer

    class ShakemapSerializer(ModelSerializer):
        class Meta:
            model = 'shakescreen.Shakemap'
            publish_fields = ('event_id', 'time', 'mag', 'lon', 'lat', 'region')

    class StationSerializer(ModelSerializer):
        class Meta:
            model = 'shakescreen.Station'
            publish_fields = ('station_ident', 'latitude', 'longitude', 'elevation')

I also verified that database inserts and update are not failing.

**Comment by jonashagstedt** [comment]
Can't see anything obviously wrong there either.

What version of Redis server are you using?

**Comment by wleev** [comment]
Redis server v=2.8.17 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=7986fa37b82c8c8b

**Comment by jonashagstedt** [comment]
It does seem like the issue is somewhere in the Redis region.
If get single etc. works then the router is fine as well as the connection between the client and SD.

Okay let's make sure subscribing is actually happening.

in your `ShakemapRouter` add the following:

    def subscribe(self, **kwargs):
        import ipdb;ipdb.set_trace()
        super().subscribe(**kwargs)  # Py3, change `super` for py2

This way we can find out if subscribing actually happens.
When it stops on the breakpoint just step through the process and see what happens.

**Comment by wleev** [comment]
It's hitting the breakpoint, when I start up the front-end. Double-checked with Redis' PUBSUB to confirm 2 existing channels 'station|' and 'shakemap|' and both have one active subscriber.

**Comment by jonashagstedt** [comment]
That would be correct.
Each user is not a subscriber in Redis (it's not how tornados-redis works), so you would only have one subscriber.

So having both `runserver` and `runsd` going, what happens if you open a shell and modify a map instance? If you put a breakpoint in the save function of `SelfPublishModel` can you walk it through and see if it gets to the point of publishing data?

**Comment by wleev** [comment]
I've tried that ( with creating ) and it moves all the way to 'model_publisher.py', but remains empty on:

        all_model_channels = publisher.get_channels(base_channel)

And as a consequence 'channels' will also remain empty, so publish never happens.

**Comment by jonashagstedt** [comment]
Can you put a breakpoint here to make sure this happens, and tell me what the base channel is:
https://github.com/jonashagstedt/swampdragon/blob/3b94b5f61648cc9a831cc62d0b0fca3f3229d81a/swampdragon/pubsub_providers/redis_publisher.py#L29

**Comment by wleev** [comment]
The base channel is 'shakemap|'. Apparently redis_publisher.py:24 is what's malfunctioning:

    channels = get_redis_cli().execute_command('PUBSUB', 'channels', '{}*'.format(base_channel))

If I run it manually I get back one entry 'shakemap|', when executed from swampdragon it returns an empty array.

**Comment by jonashagstedt** [comment]
Okay seems like we are getting closer to the issue.

Can you check the host etc. of the redis client?
Just to make sure it's not using a different host (it doesn't make sense that it would return an empty array when you run the exact same command via the redis client)

**Comment by wleev** [comment]
Checked and double-checked. All nicely using default localhost:6379 and I'm not getting any exceptions on the connect or execution of commands.

**Comment by jonashagstedt** [comment]
Can you do a `pip freeze|grep -i redis` so I can see what version of the redis client you are using.

**Comment by wleev** [comment]
redis==2.10.3
tornado-redis==2.4.18

**Comment by jonashagstedt** [comment]
That's the exact same ones as I have.

Okay can you do this:

    redis_client = get_redis_cli()
    redis_client.set('find-me', '123')

and then connect to Redis from a terminal using `redis-cli` and see if the key `find-me` is there?

**Comment by wleev** [comment]
Well, I've seem to have found the culprit. Apparently redis-py does not work with 'localhost' as it's host ip on my box. Not sure as to why this is the case, since I can use redis-cli just fine with localhost on the terminal.

I put this into my django's settings.py :

    SWAMP_DRAGON_REDIS_HOST = '127.0.0.1'

And now it's working. Sorry to have troubled you so much, seeing as swampdragon had nothing to do with it in the end. Guess I'll have to ask the redis-py people for potential causes.

Thanks for diagnostic input and for the great library.

**Comment by jonashagstedt** [comment]
No problem.
Glad you managed to resolve it.

However, I don't have any issues with localhost (not in OSX and not on Ubuntu).
Do you have anything setup in your hosts file that could possible cause an issue? Shouldn't be but might be worth checking.

I'm glad it's working though.

Cheers

**Comment by wleev** [comment]
Something changed which made it dysfunctional, not sure what though. The hosts file looks good and 'localhost' is working everywhere else on the system. The workaround is not that hacky so I can live with it.

Thanks.
