### ISSUE TITLE
SelfPublishModel not always updating

### ISSUE THREAD

**Issue by dumoulinj** [jonashagstedt/swampdragon#78]
Hi,

I have a model "Dataset", and a OneToOne relationship from model "Monitoring" to "Dataset".
Both are SelfPublishModel, with correct serializers and routers, and it works as expected.

I have a Celery task that set a field "running" to True on the Monitoring instance, do something that take some time, and set the field to False when finished. Something like this:

dataset.monitoring.running = True
dataset.monitoring.save()
DO SOMETHING THAT TAKE TIME (several seconds)
dataset.monitoring.running = False
dataset.monitoring.save()

Then, in an AngularJS frontend, I subscribe to the channel, receive the messages, and update the corresponding models.

The problem is that my frontend only receive the update message after the running field is set to True, but not the second one when the running field is set to False...

Thanks for your help

**Comment by jonashagstedt** [comment]
Without seeing how you have wired all this up I have no idea where to even begin.

What does your router look like? How are you implementing the front end?
If you can share some code I might be able to help you

**Comment by dumoulinj** [comment]
Thanks for your quick answer. 

Here is my code:

The models:
class Dataset(SelfPublishModel, models.Model):
    serializer_class = DatasetSerializer
    name = models.CharField(max_length=50, unique=True)

class DatasetMonitoring(SelfPublishModel, models.Model):
    serializer_class = DatasetMonitoringSerializer
    running = models.BooleanField(default=False)
    dataset = models.OneToOneField(Dataset, primary_key=True, related_name='monitoring')

The serializers:
class DatasetSerializer(ModelSerializer):
    class Meta:
        model = 'datasets_manager.Dataset'
        publish_fields = ('id', 'name')
        update_fields = ('id', 'name')

class DatasetMonitoringSerializer(ModelSerializer):
    class Meta:
        model = 'datasets_manager.DatasetMonitoring'
        publish_fields = ('running')

The routers:
class DatasetRouter(ModelRouter):
    route_name = 'dataset'
    serializer_class = DatasetSerializer
    model = Dataset

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])

    def get_query_set(self, **kwargs):
        return self.model.objects.all()

class DatasetMonitoringRouter(ModelPubRouter):
    route_name = 'dataset_monitoring'
    serializer_class = DatasetMonitoringSerializer
    model = DatasetMonitoring
    valid_verbs = ['get_single', 'subscribe', 'unsubscribe']

    def get_object(self, **kwargs):
        return self.model.objects.get(dataset__id=kwargs['dataset_id'])

The angularJS code (in coffee script)
$scope.datasetChannel = 'datasetChannel'
$scope.datasetMonitoringChannel = 'datasetMonitoringChannel'

$dragon.onReady(() ->
    $dragon.subscribe('dataset', $scope.datasetChannel, {id: $scope.datasetId}).then((response) ->
        $scope.datasetDataMapper = new DataMapper(response.data)
    )

    $dragon.subscribe('dataset_monitoring', $scope.datasetMonitoringChannel, {dataset__id: $scope.datasetId}).then((response) ->
        $scope.datasetMonitoringDataMapper = new DataMapper(response.data)
    )    

    $dragon.getSingle('dataset', {id:$scope.datasetId}).then((response) ->
        $scope.dataset = response.data
    )

    $dragon.getSingle('dataset_monitoring', {dataset_id:$scope.datasetId}).then((response) ->
        $scope.datasetMonitoring = response.data
    )        
)

$dragon.onChannelMessage((channels, message) ->
    if (indexOf.call(channels, $scope.datasetChannel) > -1)
        console.log("dataset changed!")
        console.log(message)
        $scope.$apply(() ->
            $scope.datasetDataMapper.mapData($scope.dataset, message)
        )

    if (indexOf.call(channels, $scope.datasetMonitoringChannel) > -1)
        console.log("monitoring changed!")
        console.log(message)
        $scope.$apply(() ->
            $scope.datasetMonitoringDataMapper.mapData($scope.datasetMonitoring, message)
        )    
)


The Celery task:
@shared_task
def run_task(dataset_id):    
    dataset = Dataset.objects.get(pk=dataset_id)
    dataset.monitoring.running = True
    dataset.monitoring.save() # The frontend gets immediately the update message
    
    # Do something
    time.sleep(4)

    print dataset.monitoring.running # Output: True
    dataset.monitoring.running = False
    dataset.monitoring.save() # The frontend does not get any update message
    print dataset.monitoring.running # Output: False
    
    return result

I also tried to make the task directly in a router and not in a Celery task, and it was exactly the same. I only receive the first message saying that the datasetMonitoring object has been updated and the running value is true, but no message after the second update. If I launch the task a second time, same behavior...

Hope the code helps!
Thanks!

**Comment by jonashagstedt** [comment]
Have you tried to console.log every channel message, and also write something like a management command to manually be able to change the bool value and save so you can monitor the console output?

I can't see anything directly wrong but the code is a bit hard to read when it's not all formatted.

**Comment by dumoulinj** [comment]
I was formatting my previous message while you were reading it, sorry!

So, in a python console, if do dataset_instance.save(), the frontend $dragon.onChannelMessage() is called, but when I do monitoring_instance.save() it is never called! Something wrong with the way I subscribe?

**Comment by jonashagstedt** [comment]
I can't see anything obvious wrong.

There is one thing though:

    class DatasetMonitoringSerializer(ModelSerializer):
        class Meta:
            model = 'datasets_manager.DatasetMonitoring'
            publish_fields = ('running')

This one: `publish_fields = ('running')` should be `publish_fields = ('running', )` (need the comma since it's a collection)

**Comment by jonashagstedt** [comment]
Another thing I see:

In JavaScript yo have `{dataset__id: $scope.datasetId}` when subscribing, however in your Py code you have `dataset__id=kwargs['dataset_id']`

**Comment by dumoulinj** [comment]
I've corrected those two small errors but still not working correctly.
I should have made some mistake somewhere... but can't find it!

I think I will move all the Monitoring fields directly in the Dataset model since this one is working correctly. 

Thank you very much for your help, and many thanks for your great library!

**Comment by jonashagstedt** [comment]
No problem (and thank you).

You could use `ipdb` to put a breakpoint in the self publishing models `_publish` function and see if it it's called the second time (`ipdb` is your friend!)

**Comment by dumoulinj** [comment]
I found a very strange behavior, but only with boolean fields.

If I do:
```python
dataset = Dataset.objects.get(pk=1)
dataset.running = True
dataset.save()
time.sleep(2)
dataset.running = False
dataset.save()
```

I get the correct update on the first save(), but the second save() sends the same message, with running = True

The workaround:
```python
dataset = Dataset.objects.get(pk=1)
dataset.running = True
dataset.save()
time.sleep(2)

dataset = Dataset.objects.get(pk=1)
dataset.running = False
dataset.save()
```

If I re-get the model instance, it works as expected!! Any Idea why it is working with strings but not with booleans?

Best regards

**Comment by jonashagstedt** [comment]
You might have come across an interesting bug here.
I'm going to write up a test to see if it is an actual bug and I can do a hotfix for this

**Comment by jonashagstedt** [comment]
Fixed and on pypi as 0.4.2.1

**Comment by jonashagstedt** [comment]
Let me know if the fix is working for you.

**Comment by dumoulinj** [comment]
Yes! Working!

I was not able to find the 0.4.2.1 version on pypi
```
pip install swampdragon==0.4.2.1
```
so I installed it using the git repo like this
```
pip install -e git+https://github.com/jonashagstedt/swampdragon.git@0.4.2.1#egg=swampdragon
```

Again, many thanks for your reactivity and for this great library!

**Comment by jonashagstedt** [comment]
Forgot to update the setup file, all sorted and published to pypi
