### ISSUE TITLE
Version 0.4.2.1 requires Django < 1.8

### ISSUE THREAD

**Issue by ppawlak** [jonashagstedt/swampdragon#80]
Here : https://github.com/jonashagstedt/swampdragon/blob/0.4.2.1/setup.py#L22

After doing a *pip install swampdragon* Django got downgraded from 1.8.1 to 1.7.8 and stopped working because I am using the new django.contrib.postgres app.
Please fix :)

**Comment by jonashagstedt** [comment]
This is fixed in 0.4.3
Just install from git as 0.4.3 has DRF serializer support that isn't entirely tested

**Comment by jonashagstedt** [comment]
Actually this issue will remain in 0.4.3, I will fix this right away

**Comment by jonashagstedt** [comment]
fixed

**Comment by wengole** [comment]
Is there a reason to limit the version to < anything?

**Comment by jonashagstedt** [comment]
Yes since 0.4.2 isn't compatible with Django 1.8 
0.4.3 is but it's not ready for release yet.

0.4.3 can probably be used but the DRF serializers aren't extensively tested

**Comment by ppawlak** [comment]
0.4.2 isn't compatible with Django 1.8 ? I though it was, as issue #54 says.
I actually have it working (after re-installing Django 1.8) but I may only be using a small part of Swamp Dragon.
Thanks for this cool project by the way :)

**Comment by jonashagstedt** [comment]
Right you are!
0.4.2 is Django 1.8 compatible!
I'll patch this right away and push an update to pypi

**Comment by jonashagstedt** [comment]
Sorted. a pip install of swampdragon should now support Django 1.8 (and not force a downgrade).

**Comment by ppawlak** [comment]
Thanks for the quick fix!
You saved my deployment! :)
