### ISSUE TITLE
Can't get channel name in onChannelMessage()

### ISSUE THREAD

**Issue by ppawlak** [jonashagstedt/swampdragon#83]
I am not sure whether this is a bug or a bad use of the JS client.

Here is my code :

```
swampdragon.ready(function () {
    subscribe();
});

function subscribe () {
    var channels = ["downloads", "updates"];
    for (var i = 0; i < channels.length; i++) {
        var channel = channels[i];
        swampdragon.subscribe('dashboard', channel, null, function (context, data) {
            if(data['action'] === "subscribe") {
                update_stats(data['local_channel'], data['stats']);
            }
        }, function (context, data) {
            console.log('subscription failed to channel ' + channel);
        });
    }
}

swampdragon.onChannelMessage(function (channel, message) {
    console.log('onChannelMessage: ' + channel);
    update_stats(channel,message.data);
});

```

When *onChannelMessage* is called *channel* is always *undefined*. Using JS debugger I could find out that the problems occurred internally in *getLocalChannels* because the variable *_channels* is empty. 
I made a [dirty fix](https://github.com/Ponytech/swampdragon/commit/131ac136999bafe475a2dc51f47cfb664ef854eb) to get it working but I'm not sure I am doing things right.

BTW: I am using version 0.4.2.2

**Comment by jonashagstedt** [comment]
`swampdragon.onChannelMessage` should have channels (plural) as argument, so the function you pass to onChannelMessage should be `function (channels, data)`.

what does your router look like?
You are subscribing to the same router twice (admittedly with different channel names but it's still the same router)

**Comment by ppawlak** [comment]
My router code is : 

	class DashboardRouter(BaseRouter):
		route_name = 'dashboard'

		def make_channel_data(self, client_channel, server_channels, action):
			data = super(DashboardRouter, self).make_channel_data(client_channel, server_channels, action)
			if client_channel == "downloads":
				data['stats'] = get_stats(Download)
			if client_channel == "updates":
				data['stats'] = get_stats(Update)
			self.send(data)

		def get_subscription_channels(self, **kwargs):
			return ['downloads', 'updates']


Is it a misunderstood of what a channel is for? 
Should I make 2 routers to handle the 2 types of info I want to send ?

**Comment by jonashagstedt** [comment]
I think I see the issue.

`make_channel_data` composes channel information, it's not a function you would have to override.

If your workflow is as follows:

1.  User opens a dashboard
2.  User should get the latests "Downloads" and "Updates" data
3.  Use should receive instant updates as soon as "Downloads" or "Updates" changes

Then you would write this as follows:

    # routers

    class DashboardRouter(BaseRouter):
        route_name = 'dashboard'
        valid_verbs = ['subscribe', 'get_dashboard']

        def get_subscription_channels(self, **kwargs):
            return ['dashboard']

        def get_dashboard(self, **kwargs):
            data = {}
            data['stats'] = get_stats(Download)
            data['stats'] = get_stats(Update)
            self.send(data)



    // JavaScript

    swampdragon.ready(function () {
        subscribe();
        getInitialDashboardData();
    });

    function subscribe () {
        // This is your local channel, and it maps to all channels returned by the router
        // as you (can) have multiple channels mapping to one local channel.
        // multiple channels are more useful when you have different filters for models so it doesn't
        // really apply in this application
        var channel = "dashboard-chan";

        swampdragon.subscribe('dashboard', channel, null, function (context, data) {
            // Successfully subscribed
        }, function (context, data) {
            console.log('subscription failed to channel ' + channel);
        });
    }


    // Get the initial dashboard data 
    // if we don't do this then you won't have any data
    // until something changes so it's good practice to get this
    function getInitialDashboardData () {
        swampdragon.callRouter("dashboard", 'get_dashboard', {}, function (data) {
            // Handle the dashboard data
            console.log(data);
        });
    }

    // Since we only have one channel subscribed to, we don't need to 
    // care which channel it is etc.
    // however if you have more channels / routers then you should check
    // which channel you are receiving data on
    swampdragon.onChannelMessage(function (channels, message) {
        update_stats(channel, message.data);
    });

**Comment by ppawlak** [comment]
This is exactly the workflow I wanted : thanks for the code !
