### ISSUE TITLE
Misspeled settings variable in documentation 'swamp_dragon_host'

### ISSUE THREAD

**Issue by yguarata** [jonashagstedt/swampdragon#87]
Hi there,

I think there is an error in settings documentation (http://swampdragon.net/documentation/settings/):

    // ouput http://localhost:9999 assuming you are running your server on that url
    console.log(window.swamp_dragon_host);

The variable does not exist. Actually, it should be swampdragon_host. I am using SwampDragon-0.4.2.2.

Thanks.

**Comment by jonashagstedt** [comment]
Good find! Updated
