### ISSUE TITLE
SelfPublishModel with field primary_key=True and default

### ISSUE THREAD

**Issue by fatrix** [jonashagstedt/swampdragon#89]
I'm having a Model for self publishing:

    class MyModel(SelfPublishModel, models.Model):
        modelid = models.IntegerField(primary_key=True, default=create_pk)

in `swampdragon/models.py` on line 83 a check is done with `if not self.pk` to differ if the instance is created or updated. But with a default primary key set on the model, the primary key seems to be set at this state already.

Would it be an acceptable solution to change the check to `if self._state.adding`?

If you agree, I can send a pull request.

**Comment by jonashagstedt** [comment]
If you wouldn't mind writing some tests for it and as long as it doesn't break anything, feel free to do it and I'll review it asap.

**Comment by fatrix** [comment]
OK, I just figured out how to run the tests (it doesn't seem to be documented anywhere how somebody can run the tests for the project).

    tox

I will go threw the tests and will come with a pull request.

**Comment by jonashagstedt** [comment]
I just ran the tests and they fail for me.

Good point about running the tests, I've updated the README to mention Tox

**Comment by jonashagstedt** [comment]
Fixed in 0.4.3 branch.
However, as per this ticket: https://code.djangoproject.com/ticket/24691 I am unsure if it would be an issue if it's a UUID (self.pk check would be an issue of course)
