### ISSUE TITLE
Django Rest Framework object has no attribute 'base_fields'  0.4.3

### ISSUE THREAD

**Issue by sylflo** [jonashagstedt/swampdragon#93]
I'm trying to use DRF with a simple mode contains only a char field and the serializer_class of course.
I tried first to use only the serializers of SwampDragon it works really well.
But when I used the serializers of DRF I've got an error.

```
'TestTextSerializer' object has no attribute 'base_fields'
```

In my models.py I've got:

```
from django.db import models
from swampdragon.models import SelfPublishModel
from todo.serializers import TestTextSerializer

class TestText(SelfPublishModel, models.Model):
    serializer_class = TestTextSerializer
    title = models.CharField(max_length=255)
```

And in my serializers,py, I've got 

```
from rest_framework import serializers

class TestTextSerializer(serializers.ModelSerializer):
    class Meta:
        model = 'todo.TestText'
        fields = ('title',)
        publish_fields = ('title',)
```

I found this when doing a research https://groups.google.com/forum/#!topic/django-rest-framework/LTMUqLxPbqM,
So I tried this in my serializers.py

```
class TestTextSerializer(serializers.ModelSerializer):
    def __init__(self, *args, **kwargs):
        fields = kwargs.pop('title', None)
        super(TestTextSerializer, self).__init__(*args, **kwargs)

        if fields is not None:
            # Drop any fields that are not specified in the `fields` argument.
            allowed = set(fields)
            existing = set(self.fields.keys())
            for field_name in existing - allowed:
                self.fields.pop(field_name)
```

But I've got the exact same error
```
'TestTextSerializer' object has no attribute 'base_fields'
```

**Comment by jonashagstedt** [comment]
I haven't been able to replicate this.

One thing I see that doesn't look right is this: 

    class TestTextSerializer(serializers.ModelSerializer):
        class Meta:
            model = 'todo.TestText'  <-- This isn't possible in DRF

You can not have a string as a model in DRF (this should throw `AttributeError: 'str' object has no attribute '_meta'`

Could you share some more code around this (like your router) or even better, write a test case for this in the 0.4.3 branch so I can see it failing.
That way I can fix this for sure, but as of now I can not replicate this.

**Comment by tomchristie** [comment]
> as of now I can not replicate this.

I'd suggest closing this - no point in tracking issues that cannot be verified or replicated.
You can always reopen if more information come to light.

**Comment by jonashagstedt** [comment]
Good point

**Comment by tomchristie** [comment]
:smile:
