### ISSUE TITLE
Conception with a form

### ISSUE THREAD

**Issue by sylflo** [jonashagstedt/swampdragon#94]
First thanks to your project, it's really cool.

I've got a question about form. I'm doing a one page.

My urls.py
```
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='home'),

    url(r'^admin/', include(admin.site.urls)),
]
```

In my template I call others templates like this (I'm making an app by section)
```
{% include "contact/contact.html" %}
```

So the template contact.html is in app, In this on I've got 

models.py
```
class ContactSocialNetwork(SelfPublishModel, models.Model):
    serializer_class = ContactSocialNetworkSerializer
    phone = PhoneNumberField()
    mail = models.EmailField()
    office = models.CharField(max_length=255)
    facebook = models.URLField(default=None, blank=True)
    twitter = models.URLField(default=None, blank=True)
    google_plus = models.URLField(default=None, blank=True)
    linkedin = models.URLField(default=None, blank=True)
```

serializers.py
```
class ContactSocialNetworkSerializer(ModelSerializer):
    class Meta:
        model = 'contact.ContactSocialNetwork'
        publish_fields = ('mail', 'office', 'facebbok', 'twitter', 'google_plus', 'linkedin')

    def serialize_phone(self, obj):
        phone = "+"
        phone += str(obj.phone.country_code)
        phone += str(obj.phone.national_number)
        return '{} {}'.format(phone, "")
```
routers.py
```
class ContactSocialNetworkRouter(ModelRouter):
    valid_verbs = BaseRouter.valid_verbs + ['say_hello']
    route_name = 'contact-social-network'
    serializer_class = ContactSocialNetworkSerializer
    model = ContactSocialNetwork

    def create(self, **kwargs):
        print("toto")

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])

    def get_query_set(self, **kwargs):
        return self.model.objects.all()

route_handler.register(ContactSocialNetworkRouter)
```

And finally my controller.js
```
var ContactController = angular.module('ContactController', []);

ContactController.controller('ContactCtrl', ['$scope', '$dragon', function($scope, $dragon) {

    $scope.contact = {};
    $scope.channel = 'contact-social-network';

    $dragon.onReady(function() {


            $dragon.subscribe('contact-social-network', $scope.channel, {id:1}).then(function(response) {
                console.log("Subscribe Social Network");
           $scope.dataMapper = new DataMapper(response.data);
        });


         $dragon.getSingle('contact-social-network', {id:1}).then(function (response) {
            console.log("get Single Contact = ", "response.data = ", response);

           $scope.contact = response.data;

        });


        $dragon.create('contact-social-network', {}).then(function (response) {
            console.log("Createt = ", "response.data = ", response);

           $scope.contact = response.data;

        });
    });

      $dragon.onChannelMessage(function (channels, message) {
        if (indexOf.call(channels, $scope.channel) > - 1) {
            $scope.$apply(function() {
               $scope.dataMapper.mapData($scope.contact, message)
            });
        }
    });

}]);
```

So the model it's working really well.
But I don't know how to create a form in a proper way. What is the best method create a new verb in a new serializer. Or there is a better way ?

**Comment by jonashagstedt** [comment]
Since you are using the `SelfPublishModel` there are a myriad of ways you can do this.

*  You can call `$dragon.create` (or `update`)
*  You can create a normal html form that posts to a view (though this would make it less of a one-page app)

There is no "proper" way to create a form for SD. You simply need to get form data and handle the errors.

If you are using angular you can just bind a model to inputs and then handle the errors.
Like here: https://github.com/jonashagstedt/swampdragon/blob/master/selfpub_example/selfpub_example/templates/home.html#L30
Just handle the errors as well.

**Comment by sylflo** [comment]
I should look at the examples more carefully.

If I want to create a form from a model.
I need to get to the view for create the form right ?

So I have to use this solution:

> You can create a normal html form that posts to a view (though this would make it less of a one-page app)

**Comment by jonashagstedt** [comment]
I think I might not have explained my self too well.
I meant you could have a normal Django view with a form and a template that creates the model.
You don't specifically have to use a router to create the model as it's a self publishing model (i.e it will trigger a publish when it's updated).

Alas in this case I would simply output the form as you would do with any JavaScript framework when you want to post data.

    <input type="text" ng-model="mymodel.property_a">
    <span ng-bind="error.property_a"></span>

    <input type="text" ng-model="mymodel.property_b">
    <span ng-bind="error.property_b"></span>

    <button ng-click="call create on router here">Create</button>

Then you can simply call `$dragon.create(... $scope.mymodel, success, fail);`
and if it fails you simply assign the errors to `$scope.errors` 

There might be some Django form renderers or such for Angular as well, I haven't looked in to that, but unless you have massive forms I would say it's rather simple to just output the html manually.

**Comment by sylflo** [comment]
Thanks to you, I solved my problem and by the way the documentation is really good.

>There might be some Django form renderers or such for Angular as well, I haven't looked in to that, but unless you have massive forms I would say it's rather simple to just output the html manually.

Ok, I don't need this right now. I'm really interested to use SwampDragon for a bigger project tough I can manage to type all form by hand.

Many thanks to you.

**Comment by jonashagstedt** [comment]
Wonderful, I'll close this.

I have tinkered with doing form renderers in JavaScript for this purpose but I really don't want yet another package to maintain. If you do come up with a solution you are happy with feel free to share it here.

We are quite spoiled with Django and the form renderers, with most other languages you have to manually output every single form element for each form so it's not the end of the world to have to do this.

I find that I have to do a lot of manual output with forms in Django in the end, depending on clients design.
