### ISSUE TITLE
Is it possible to send notifications to specific clients?

### ISSUE THREAD

**Issue by sibe7691** [jonashagstedt/swampdragon#95]
Hi,

I am trying to build a messenger/whatsapp like service.

If i have the following model:

    class Message(models.Model, SelfPublishModel):
        to=models.ForeignKey(User)
        message=models.CharField(max_length=10000)

Is it possible to send the real-time update to the user represented by the "to" variable?
Given that the user is currently subscribing of course.

/ Simon

**Comment by jonashagstedt** [comment]
Sure is.

The self publish model only knows that it should be published upon change (or any CRUD operation), so it's up to the router.

    class MessageRouter(ModelRouter):
        ...

        def get_subscription_contexts(self, **kwargs):
            return {'to__id': self.connection.user.pk} 

This will generate a unique channel for each user subscribing.
**Note** you need swampdragon-authto be able to use `self.connection.user'.

**Comment by sibe7691** [comment]
Looks neat! will try it thanks!

**Comment by jonashagstedt** [comment]
Closing this issue for now. Feel free to reopen the issue if you need more info
