### ISSUE TITLE
How to fallback if websocket doesn't respond?

### ISSUE THREAD

**Issue by janezkranjc** [jonashagstedt/swampdragon#96]
I am using angularJS to connect to the websocket and I want to know if there is a way ti implement a sort of $dragon.onError to coexist with onReady, because if the websocket connection is somehow down I wish to fallback to ajax calls with timed intervals.

**Comment by jonashagstedt** [comment]
Interesting solution. 
There isn't one at this moment in time but it would be trivial to expose the connection error.

I am currently too busy with the DRF serializer work and my day job to get this in now but if more people want this feature I'll consider adding it to for 0.4.3.

**Comment by jonashagstedt** [comment]
I've added `onClose` to the angular service in the 0.4.3 branch.
